### ISSUE TITLE
 Please add proper license

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#1]
Hello

Would it be possible to clarify the license of this project? Is it open source (GPL, BSD, MIT)? Otherwise there're unclear conditions for contribution if that welcome.

Thank you for the project!

**Comment by wladich** [comment]
Извините за долгое молчание -- забыл настроить оповещения с проекта.

Про лицензию я не совсем понимаю, как правильно. Допустим, я хочу MIT или даже Unlicense. Но в зависимостях у меня есть GPL-2, причём зависимость лежит в vendor, а GPL требует, чтобы весь проект, который использует такую зависимость был тоже под GPL. Но я GPL не хочу...
В общем непонятно.

**Comment by sikmir** [comment]
Как понимаю речь идет об [js-deflate](https://github.com/dankogai/js-deflate/), да, к сожалению он "заражает" все проект GPL, так как GPL носит вирусный характер. Единственный выход это как-то сделать его не частью проекта, а внешней зависимостью, если нельзя совсем избавиться.
