### ISSUE TITLE
Многоугольники

### ISSUE THREAD

**Issue by Deeoke256** [wladich/nakarte#1036]
Приветствую!
Возможно, пишу не туда, но очень бы хотелось видеть в отличном проекте nakarte возможность рисования на карте замкнутых фигур - многоугольник, круг, с цветной заливкой. 
Ну и конечно, возможность автоматической прокладки пути по дороге тоже бы сильно облегчило жизнь туристам.
С уважением,
Ди.

**Comment by sikmir** [comment]
> Ну и конечно, возможность автоматической прокладки пути по дороге тоже бы сильно облегчило жизнь туристам.

#10

**Comment by wladich** [comment]
Про рисование - я считаю, что конкретно в nakarte это излишне.
Про автопрокладку - sikmir правильно заметил, что issue уже есть, может быть когд-нибудь удасться сделать...
