### ISSUE TITLE
Порядок следования слоев

### ISSUE THREAD

**Issue by Xeenych** [wladich/nakarte#107]
Я сделал вот такой кастомный слой и хочу, чтобы он накладывался поверх Topo 500.
Но topo500 стоит в списке ниже моего слоя и полностью его накрывает.

https://nakarte.tk/#m=15/42.06102/77.81754&l=O/Wp/-cseyJuYW1lIjoiQ3VzdG9tIGxheWVyIiwidXJsIjoiaHR0cDovL3hlZW55Y2gubmV4dGdpcy5jb20vYXBpL2NvbXBvbmVudC9yZW5kZXIvdGlsZT96PXt6fSZ4PXt4fSZ5PXt5fSZyZXNvdXJjZT0xMCIsInRtcyI6ZmFsc2UsInNjYWxlRGVwZW5kZW50IjpmYWxzZSwibWF4Wm9vbSI6IjE4IiwiaXNPdmVybGF5Ijp0cnVlfQ==

**Comment by sikmir** [comment]
Already done in #95.

**Comment by Xeenych** [comment]
Работает!
