### ISSUE TITLE
Слой mapy.cz tourist отвалился

### ISSUE THREAD

**Issue by snooppr** [wladich/nakarte#1077]
Остальные слои работают.

**Comment by wladich** [comment]
Я его починил 5 часов назд в #1076, у меня он сейчас работает.
Попробуйте Ctrl-F5.
Если не поможет, покажите пожалуйста Console в DevTools в браузере

**Comment by snooppr** [comment]
FF
> На этой странице используется нестандартное свойство «zoom». Попробуйте использовать calc() в соответствующих значениях свойств или использовать «transform» вместе с «transform-origin: 0 0». [nakarte.me](https://nakarte.me/#m=8/49.73868/33.45886&l=Czt)
Version: 2022-11-29_07:57:51-master-030d304 [instrument.ts:124:32](webpack:///src/instrument.ts)
UID: 11000000A5F38563FA3FBE8002E91803 [instrument.ts:124:32](webpack:///src/instrument.ts)
Запрос из постороннего источника заблокирован: Политика одного источника запрещает чтение удаленного ресурса на https://sentry.io/api/144904/envelope/?sentry_key=11ff06bc986e46aaa40d5ea406a14aaa&sentry_version=7. (Причина: не удалось выполнить запрос CORS). Код состояния: (null).

Chrome

> fetch.ts:59          POST https://sentry.io/api/144904/envelope/?sentry_key=11ff06bc986e46aaa40d5ea406a14aaa&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:59
t @ syncpromise.ts:54
(anonymous) @ fetch.ts:58
add @ promisebuffer.ts:49
e._sendRequest @ fetch.ts:56
t.sendSession @ base.ts:88
t.sendSession @ basebackend.ts:142
t._sendSession @ baseclient.ts:287
t.captureSession @ baseclient.ts:183
t._sendSessionUpdate @ hub.ts:484
t.captureSession @ hub.ts:419
f @ sdk.ts:201
(anonymous) @ sdk.ts:232
e.init @ sdk.ts:100
11512 @ index.js:40
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mc.mapserver.mapy.cz/turist-m/retina/8-152-87:1          GET https://mc.mapserver.mapy.cz/turist-m/retina/8-152-87 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mc.mapserver.mapy.cz/turist-m/retina/8-151-88:1          GET https://mc.mapserver.mapy.cz/turist-m/retina/8-151-88 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
ma.mapserver.mapy.cz/turist-m/retina/8-151-86:1          GET https://ma.mapserver.mapy.cz/turist-m/retina/8-151-86 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
ma.mapserver.mapy.cz/turist-m/retina/8-152-88:1          GET https://ma.mapserver.mapy.cz/turist-m/retina/8-152-88 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
ma.mapserver.mapy.cz/turist-m/retina/8-150-87:1          GET https://ma.mapserver.mapy.cz/turist-m/retina/8-150-87 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
ma.mapserver.mapy.cz/turist-m/retina/8-153-87:1          GET https://ma.mapserver.mapy.cz/turist-m/retina/8-153-87 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mb.mapserver.mapy.cz/turist-m/retina/8-151-87:1          GET https://mb.mapserver.mapy.cz/turist-m/retina/8-151-87 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mb.mapserver.mapy.cz/turist-m/retina/8-152-86:1          GET https://mb.mapserver.mapy.cz/turist-m/retina/8-152-86 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mb.mapserver.mapy.cz/turist-m/retina/8-150-88:1          GET https://mb.mapserver.mapy.cz/turist-m/retina/8-150-88 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mb.mapserver.mapy.cz/turist-m/retina/8-153-88:1          GET https://mb.mapserver.mapy.cz/turist-m/retina/8-153-88 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mc.mapserver.mapy.cz/turist-m/retina/8-150-86:1          GET https://mc.mapserver.mapy.cz/turist-m/retina/8-150-86 net::ERR_NAME_NOT_RESOLVED
Image (async)
createTile @ TileLayer.js:155
createTile @ index.js:118
_addTile @ GridLayer.js:749
_update @ GridLayer.js:646
_setView @ GridLayer.js:513
_resetView @ GridLayer.js:485
onAdd @ GridLayer.js:139
onAdd @ index.js:89
_layerAdd @ Layer.js:106
whenReady @ Map.js:1355
addLayer @ Layer.js:164
unserializeState @ Leaflet.Control.Layers.js:48
unserializeState @ index.js:251
enableHashState @ leaflet.hashState.js:23
e.setUp @ App.js:150
11512 @ index.js:60
f @ bootstrap:19
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
f.O @ chunk loaded:25
(anonymous) @ .*\.json$ chunkName: cutline-[request] namespace object:51
t @ jsonp chunk loading:73
(anonymous) @ app.010e2b17.js:2
mc.mapserver.mapy.cz/turist-m/retina/8-153-86:1          GET https://mc.mapserver.mapy.cz/turist-m/retina/8-153-86 net::ERR_NAME_NOT_RESOLVED

**Comment by wladich** [comment]
Да, поторопился и не поправил URL-y для ретины.
Поправил в #1078, обновите страницу.

**Comment by snooppr** [comment]
Хорошая оперативная работа.
