### ISSUE TITLE
Добавить обработку файлов формата GeoJSON

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#1096]

**Comment by myadzel** [comment]
[test.geojson.zip](https://github.com/wladich/nakarte/files/10190246/test.geojson.zip)

Пример файла с 4 точками и 3 сегментами.

**Comment by myadzel** [comment]
https://github.com/wladich/nakarte/pull/1099

**Comment by wladich** [comment]
@myadzel 
Напиши пожалуйста для контекста, откуда такие файлы в реальной жизни берутся.

**Comment by myadzel** [comment]
> @myadzel Напиши пожалуйста для контекста, откуда такие файлы в реальной жизни берутся.

Например отсюда, https://geojson.io

**Comment by wladich** [comment]
Т.е. нарисовать трек в geojson.io (почему в нём?) и сохранить в geojson вместо KML? 
Или есть какой-то сценарий, который я сходу не вижу?

**Comment by myadzel** [comment]
Просто это один из форматов, который поддерживает то, что несет в себе nakarte. Конкретно для чего мне это было нужно: я работал с кадастровой картой и мне было бы удобно иметь возможность редактировать файл GeoJSON через nakarte и не использовать сторонние утилиты для конвертации GPX -> GeoJSON (и наоборот).

**Comment by wladich** [comment]
Вот об этом я и спрашиваю - какие реальные применения.
Это надо, чтобы понять, сколько человек будут это использовать и где брать реальные тестовые данные.

**Comment by wladich** [comment]
@sikmir 
А у вас какие соображения по поводу откуда такие файлы могут браться? 
(Я увидел палец от вас в начале issue и решил, что может у вас тоже есть идеи)

**Comment by sikmir** [comment]
> @sikmir А у вас какие соображения по поводу откуда такие файлы могут браться? (Я увидел палец от вас в начале issue и решил, что может у вас тоже есть идеи)

У меня они беруться из всяких экспортов, например экспортирую точки из [overpass-turbo](https://overpass-turbo.eu/), потом что-то отфильтровать с помощью `jq` и открыть бы это в nakarte. Можно конечно и в GPX сразу экспортировать, но geojson проще обрабатывать.

**Comment by wladich** [comment]
Done in #1107
