### ISSUE TITLE
Не работает слой mapy.cz 

### ISSUE THREAD

**Issue by GeorgeManukyan** [wladich/nakarte#1168]
Привет, хотел спросить, не работает слой mapy.cz это навсегда? У них довольно приятный рендер.

**Comment by wladich** [comment]
Пока сложно сказать.
Как минимум недели две (я сейчас в отпуск уезжаю), возможно больше, возможно навсегда.

**Comment by wladich** [comment]
#1169
Теперь, вероятно, на совсем

**Comment by kilonet** [comment]
а есть альтернативы? https://www.mapbox.com/maps/outdoors ?

**Comment by wladich** [comment]
- это слой из векторных тайлов, он не работает без их библиотеки (вместо которой у меня leaflet), он у меня тормозит до состояния неюзабельности и он платный.
