### ISSUE TITLE
Solved problem with Strava Heatmap on Firefox

### ISSUE THREAD

**Issue by sembruk** [wladich/nakarte#12]
After I login on Strava nakarte don't load Heatmap tiles and show message about this. I use Firefox.
Solution.
1. Click the Firefox menu button and choose `Preferences`.
1. Select the `Privacy & Security` panel and go to the **History** section.
1. In the drop-down menu next to **Accept third-party cookies** choose `From visited`.

**Comment by sembruk** [comment]
Проблема. Несмотря на то, что я авторизовался на Страве и посетил станицу Heatmap, Nakarte продолжает мне показывать сообщение о необходимости авторизоваться на Страве. Я использую Firefox.
Решение.
1. Щёлкнуть кнопку меню в Firefox и выбрать `Настройки`.
1. Выбрать панень `Приватность и Защита`.
1. В секции **История** в выпадающем меню **Принимать куки со сторонних веб-сайтов** установить `С посещённых`.

**Comment by wladich** [comment]
Печаль.
Придётся отдельную инструкцию писать, в alert такое уже не запихнёшь
