### ISSUE TITLE
Для части 360 панорам с google map не отображается метки на крате

### ISSUE THREAD

**Issue by GeorgeManukyan** [wladich/nakarte#1205]
Для части 360 панорам с google map не отображается метки на крате (синий кружочек) 
Иногда бывает открываешь карту, просто тыкаешь в пустое место и открывается 360 панорама с Гугл карт, но соответствующей метки на карте нет. 

Таким мест довольно много! 
вот например одна из них https://nakarte.me/#m=14/42.26988/44.98369&l=Co/Wh&q=N42%C2%B030'7%2C968%22%20E44%C2%B047'50%2C802%22&n2=_gw/g/42.272895/44.966591/173.9/0.0/1.0

**Comment by wladich** [comment]
Если открыть это место на карте гугла (кнопка квадратик со стрелочкой, в меню выбрать Google) и включить панорамы, то будет ровно то же самое - метки нет, но если кликнуть в нужное место, открывается панорама.
Т.е. это проблема на стороне Гугла и я здесь бессилен
