### ISSUE TITLE
OpenCycleMap: добавить параметр apikey и возможность загрузки retina-тайлов

### ISSUE THREAD

**Issue by svintuss** [wladich/nakarte#1228]
Добрый день. 

Если загружать OpenCycleMap по адресу `https://a.tile.thunderforest.com/cycle/8/150/87.png`, то по диагонали отображается надпись `API key required`. Этот ключ можно узнать, если иметь аккаунт в OpenStreetMap. 

Вы могли бы в интерфейсе добавить возможность указать `apikey`: `https://c.tile.thunderforest.com/cycle/11/1241/639@2x.png?apikey={XXXXX}`

Помимо этого, было бы здорово включить переключатель для retina-тайлов `@2x`.

**Comment by wladich** [comment]
Добавил загрузку ретина-тайлов (работает для ретина-мониторов и печати pdf).
Ключ уже использовался некоторое время назад, но пришлось его убрать, т.к. превышался лимит количества запросов для бесплатного использования, а 95 фунтов в месяц за не самую полезную карту для меня это дорого

**Comment by svintuss** [comment]
Спасибо! 

Насчет ключа  я имел в виду добавить возможность указать пользователю свой собственный, если он его знает. Чтобы не приходилось вручную добавлять новый источник.
