### ISSUE TITLE
не загружается трек с tracedetrail

### ISSUE THREAD

**Issue by kilonet** [wladich/nakarte#1230]
https://tracedetrail.fr/fr/trace/trace/205021

![image](https://github.com/wladich/nakarte/assets/535817/92bb7f5c-152e-45db-a17d-69ac6c3b556e)

**Comment by myadzel** [comment]
Что-то у них сломалось в API

https://tracedetrail.com/en/trace/geomSections/205021

**Comment by wladich** [comment]
Починил
