### ISSUE TITLE
Не показывается слой Wikimapia

### ISSUE THREAD

**Issue by dmp40** [wladich/nakarte#1234]
В какой то момент престал включаться слой Wikimapia. Очень полезная функция вашего сервиса. Почините , пожалуйста. Без него очень грустно.

**Comment by wladich** [comment]
Две недели назад викимапия заблокировала доступ с моего сервера. 
В прошлый раз, когда такое случалось, блокировка исчезла без моего участия через несколько дней.
Что с этим делать я пока не знаю

**Comment by wladich** [comment]
WIkimapia боролась с DOS-атаками и заодно заблокировала nakarte.
Попросил разблокировать, сейчас работает.
