### ISSUE TITLE
Прекращение поддержки слоя Yandex tracks

### ISSUE THREAD

**Issue by anisart** [wladich/nakarte#1237]
Яндекс отключает слой с треками в Народной карте. По факту они ввели авторизацию, и доступ есть только у сотрудников.
Вот пресс-релиз в их группе https://vk.com/wall-135388977_9619

**Comment by myadzel** [comment]
Грустные новости :-/ Это был полезный слой для прорисовки новых маршрутов.

**Comment by wladich** [comment]
Спасибо за сообщение, убрал слой
