### ISSUE TITLE
Documentation: broken urls

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#1242]
https://docs.nakarte.me/garmin.html has links to http://whiter.brinkster.net, but it's not available anymore.

https://web.archive.org/web/20220929144544/http://whiter.brinkster.net/JNX.shtml
https://web.archive.org/web/20221007182418/http://whiter.brinkster.net/Versions.shtml
https://web.archive.org/web/20191007102037/https://yadi.sk/d/Df846whhTH2mew

**Comment by wladich** [comment]
Спасибо за сообщение и за ссылки, поправил.
