### ISSUE TITLE
Crossing the antimeridian leads to invalid GPX file is generated

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#125]
### Steps to reproduce
1. Create [some track at Chukotka](https://nakarte.tk/#m=12/66.52995/-180.06626&l=M&nktl=u2x44cHcb9gsnr-D70kucg)  crossing the antimeridian:
![scr1](https://user-images.githubusercontent.com/688044/45305756-ad40fb80-b523-11e8-974d-716b7285a5e8.png)
2. Save as GPX:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="http://nakarte.tk" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" version="1.1">
	<trk>
		<name>test</name>
		<trkseg>
			<trkpt lat="66.513260" lon="-180.096474"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="66.518733" lon="-179.903870"><time>1970-01-01T00:00:01.000Z</time></trkpt>
		</trkseg>
	</trk>
</gpx>
```
3. Validate resulted gpx file against the gpx xsd schema:
```shell
$ curl -O http://www.topografix.com/GPX/1/1/gpx.xsd
$ xmllint -schema gpx.xsd test.gpx --noout
```
### Actual behaviour
```shell
test.gpx:6: element trkpt: Schemas validity error : Element '{http://www.topografix.com/GPX/1/1}trkpt', attribute 'lon': [facet 'minInclusive'] The value '-180.096474' is less than the minimum value allowed ('-180.0').
test.gpx:6: element trkpt: Schemas validity error : Element '{http://www.topografix.com/GPX/1/1}trkpt', attribute 'lon': '-180.096474' is not a valid value of the atomic type '{http://www.topografix.com/GPX/1/1}longitudeType'.
test.gpx fails to validate
```
### Expected behaviour
Well, if I've got it right, there is nothing can be done about that. Some shit happens on antimeridian (the end of world) anyway, am I right? That way it works at least in nakarte.tk. But other tools and Garmin will fail to read such GPX file. So, maybe a good idea to warn users explicitly about it?

**Comment by wladich** [comment]
Это баг, надо чинить. Кроме того, ещё и профиль высоты неправильно работает.
1. Выяснить, как должно быть правильно -- если координаты будут резко менятьсся от -179.999 до 179.999, не будут ли Гармин и прочий софт рисовать линию через весь мир?
2. Надо посмотреть, насколько сложно починить хорошо (чтобы в полилиниях хранились валидные координаты). Если сложно, то добавить костыли -- при сохранении и при запросе высоты приводить координаты к валидным.
3. Проверить, что при импорте неправильных треков мы их показываем правильно и затем сохраняем правильно
4. Проверить, что при импорте правильных треков мы не рисуем линию через весь мир.

**Comment by wladich** [comment]
Если нет штатного способа, то можно при сохранении резать сегмент по антимеридиану, получим из одного сегмента два или больше. При этом гармин будет показывать неправильную общую длину трека, зато хотя бы рисовать будет нормально.

**Comment by wladich** [comment]
по п.2 -- нормально, кажется, пока нельзя сделать: https://github.com/Leaflet/Leaflet/pull/1293

**Comment by wladich** [comment]
Протестировать, что правильно работает, если трек начинается с долготой > 180 или < 180
