### ISSUE TITLE
Надо явно обрабатывать ситуацию, если треки из Strava не публичные

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#127]

**Comment by wladich** [comment]
Раньше было нормально, сломалось недавно

**Comment by wladich** [comment]
Проблема только для незалогиненого пользователя

**Comment by wladich** [comment]
Нет, не только: https://www.strava.com/activities/1861101122

**Comment by myadzel** [comment]
Проверял уже несколько раз — работает, как ожидается.

**Comment by wladich** [comment]
Добавил обработку приватных треков

**Comment by wladich** [comment]
Добавил обработку приватных треков
