### ISSUE TITLE
Недоступность nakarte.tk. UPD: работает https://nakarte.me

### ISSUE THREAD

**Issue by tarwirdur** [wladich/nakarte#148]
Что-то с доменным именем.

```
$ dig nakarte.tk

; <<>> DiG 9.11.2-P1 <<>> nakarte.tk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59874
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nakarte.tk.			IN	A

;; AUTHORITY SECTION:
tk.			150	IN	SOA	a.ns.tk. joost\.zuurbier.dot.tk. 1540121918 10800 3600 604800 5

;; Query time: 42 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Sun Oct 21 14:40:37 MSK 2018
;; MSG SIZE  rcvd: 99

$ whois nakarte.tk

   Domain name:
      NAKARTE.TK

   Organisation:
      Freedom Registry, Inc.
      2225 East Bayshore Road #290
      Palo Alto CA 94303
      United States
      Phone: +1 650-681-4172
      Fax: +1 650-681-4173

   Domain Nameservers:
      NS01.FREENOM.COM
      NS02.FREENOM.COM
      NS03.FREENOM.COM
      NS04.FREENOM.COM

   Your selected domain name is a domain name that has been
   cancelled, suspended, refused or reserved at the Dot TK Registry

   It may be available for re-registration at http://www.dot.tk

   In the interim, the rights for this domain have been automatically
   transferred to Freedom Registry, Inc.

   Please be advised that the Dot TK Registry, Freenom and
   Freedom Registry, Inc. cannot be held responsible for any content
   that was previously available at this domain name.

   Due to restrictions in Dot TK 's Privacy Statement personal information
   about the previous registrants of the domain name cannot be released
   to the general public.

   Dot TK is proud to work with numerous governmental law enforcement
   agencies to stop spam, fraud, phishing attempts, child pornography and
   other illicit content on Dot TK websites. These agencies may contact the
   Dot TK Registry directly with any enquiries they may have regarding the
   usage of this domain by previous registrants.

   Record maintained by: Dot TK Domain Registry
```

**Comment by wladich** [comment]
https://m.facebook.com/story/graphql_permalink/?graphql_id=UzpfSTEwMDAwODU3MzU2MzczNDoxOTAzNTI1NTQ2NjA5ODc5

**Comment by wladich** [comment]
Сайт nakarte.tk работает, но временно недоступен по имени nakarte.tk (регистратор заморозил имя без объяснения причины, ждём ответа).

В качестве временного решения надо добавить следующую строчку в файл конец файла hosts на вашем компьютере:

212.24.101.247 nakarte.tk tiles.nakarte.tk elevation.nakarte.tk track.nakarte.tk proxy.nakarte.tk 

Для Линиксов — sudo vim /etc/hosts

Для Windows 10 и 8
Нажмите на клавиатуре кнопку Win
Наберите: notepad
В результатах поиска щелкните правой кнопкой мыши и выберите "Запустить от имени администратора"
В появившемся Блокноте откройте файл c:\Windows\System32\Drivers\etc\hosts
Добавьте в строку "212.24.101.247 nakarte.tk tiles.nakarte.tk elevation.nakarte.tk track.nakarte.tk proxy.nakarte.tk" без кавычек
Сохраните файл

Для Windows 7 и Vista
Кликните Старт - Все программы - Стандартные
Кликните правой кнопкой на Блокноте и выберите "Запустить от имени администратора".
Кликните "Продолжить" в диалоге с вопросом "Разрешить следующей программе внести изменения на этом компьютере?"
В появившемся Блокноте откройте файл C:\Windows\System32\Drivers\etc\hosts.
Добавьте в строку "212.24.101.247 nakarte.tk tiles.nakarte.tk elevation.nakarte.tk track.nakarte.tk proxy.nakarte.tk" без кавычек
Сохраните файл

Для Windows NT, Windows 2000, и Windows XP
Кликните Старт - Все программы - Стандартные - Блокнот
В появившемся Блокноте откройте файл C:\Windows\System32\Drivers\etc\hosts.
Добавьте в строку "212.24.101.247 nakarte.tk tiles.nakarte.tk elevation.nakarte.tk track.nakarte.tk proxy.nakarte.tk" без кавычек
Сохраните файл

**Comment by berkut-174** [comment]
Что-то изменилось ?

> 212.24.101.247

Выдаёт пустую страницу.

**Comment by wladich** [comment]
http://212.24.101.247 никогда не работал.
Надо добавить в запись в hosts и заходить на https://nakarte.tk

**Comment by wladich** [comment]
Объявление на блоге: https://nakarte-me.blogspot.com/2018/10/blog-post_25.html

**Comment by wladich** [comment]
оставляю пока блог доменом blogspot
