### ISSUE TITLE
карты UK

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#149]
На bing.com есть хорошие топографические карты UK:
https://binged.it/2PPF4un
Можно добавить, наверное.

**Comment by wladich** [comment]
По твоей ссылке я вижу что-то не похожее на топокарты. Уточни, пожалуйста, как их увидеть.
![screenshot at 2018-10-27 20-04-11](https://user-images.githubusercontent.com/1458202/47607706-a878ce00-da23-11e8-98da-3eaf417ab1c9.png)

**Comment by slazav** [comment]
Да, получается, что этот слой показывают только в UK.
Нашел вот такой текст (там есть и другие страны, но нужен ключ bing):
http://geo.inge.org.uk/gme_maps.htm

**Comment by wladich** [comment]
А там вроде ничего interesnogo больше нет:
https://msdn.microsoft.com/en-us/library/mt712700.aspx

**Comment by slazav** [comment]
В http://geo.inge.org.uk/gme_maps.htm они еще упоминают Canada, New Zealand, USA.
