### ISSUE TITLE
Если сегменты трека расположены с разных сторон от меридиана 180, то неправильно работает позиционирование карты на трек

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#155]
Такой трек получается при экспорте в gpx трека, пересекающего меридиан 180.
При клике на имени трека карта позиционируется на весь мир

**Comment by tarwirdur** [comment]
Неправильное поведение при открытии старых (предположительно) сохраненных треков:

https://nakarte.me/#l=Otm/N&m=4/57.72762/46.75781&nktl=g9DLWicjbx6XiZ3XxP7fFw

Если сохранить трек как gpx и загрузить заново - все нормально: https://nakarte.me/#m=4/68.28565/137.63672&l=O&nktl=sWzPFO4avXuv3DCwVyKMsg

Смотрю самые большие модули дельт долготы из треков:
```
 $ tail -c +2 old_file.nkrt | protoc --decode TrackView nktk.proto | grep lons | grep -Po  "\d+" | sort -h | tail -n 5
13559
6531058
7935675
16624486
16657913

$ tail -c +2 new_file.nkrt | protoc --decode TrackView nktk.proto | grep lons | grep -Po  "\d+" | sort -h | tail -n 5
105464
6531058
7935675
8388607
8388607
```

Попробовал в функцию `deltaDecodeSegment` добавить модуль по `±(180*arcUnit)`?

Т.е. как-то так:
```diff
+function normalizeLonDelta(deltaLon) {
+  const mod = ((1 << 24) - 1);
+  return ((deltaLon+mod/2) % mod) - (mod/2);
+}
...
         encodedLat += deltaLats[i];
-        encodedLon += deltaLons[i];      
+        encodedLon += normalizeLonDelta(deltaLons[i]);
...
```

Но после этого стало ещё хуже:

![kam](https://user-images.githubusercontent.com/8180494/67897786-265c4180-fb70-11e9-8946-7406f559c7bd.png)

**Comment by wladich** [comment]
А что-нибудь известно про историю этого трека? Судя по логам, загрузили его в базу 16 сентября этого года.

**Comment by ShashkovS** [comment]
Это мои знакомые колесили на велосипедах с findmespot'ом. Точки, которые возвращает API findmespot'а, были собраны в один gpx без какой-либо обработки координат.

**Comment by wladich** [comment]
1. Проблема не в загрузке трека по ссылке, а в исходном gpx. Загрузку сохраненных отдельно чинить не надо.
2. Преобразование координат для правильного перехода через 180 меридиан при загрузке треков, похоже, не делается; надо повнимательнее посмотреть но скорее всего нет. Преобразование есть только при экспорте (разрезание сегмента пересекающего 180 меридиан) и при редактировании / отображении.
3. Сохранение в gpx убирает проблему, т.к. при экспорте сегменты режутся по 180 меридиану.

**Comment by wladich** [comment]
Вынес в #258

**Comment by wladich** [comment]
Исправлено в #387
