### ISSUE TITLE
Отображение точки по URL, передаваемому в качестве входного параметра при вызове сайта

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#157]
Задача такая: у меня во всяких фотоальбомах генерится ссылка на maps.google.com (например, http://slazav.mccme.ru/shpitz18/11157-61.htm ). Хотелось бы научиться делать похожее с помощью nakarte (желательно с масштабом и слоями, и без предварительной загрузки хэша на сервер). Можно ли сейчас такое делать?

**Comment by wladich** [comment]
А что должно получиться?
 - новый трек с одной путевой точкой
 - некая новая сущность

**Comment by slazav** [comment]
Ну, например, новый трек с одной точкой. Сущности плодить не хочется, наверное.
Раньше, я так понимаю, можно было запаковать точку каким-то способом (который я так и не выучил) и встравить в url. Работает ли такое сейчас? Описано ли это где-нибудь?

**Comment by wladich** [comment]
Да, параметр nktk (в который передаётся base64 с данными трека) по-прежнему работает
Пример: https://nakarte.me/#m=13/50.62001/29.24217&l=O&nktk=RAoECAMQARIcCgVIZWxsbxoTCLj7nwIQ1qamARoHGgVXb3JsZA==

Описания нет, промерно так
 - Делаем протобуф по схеме, сериализуем
   https://github.com/wladich/nakarte/blob/master/src/lib/leaflet.control.track-list/lib/nktk.proto
 - Энкодим в url-safe base64
 - Вставляем как значение параметра nktk

Коментарии по протобуфу: 
 - корневой объект TrackView, в нём View и Track
 - Во View значения цветов 0-5 (или 1-6, надо проверить), в том же порядке, как в контроле трека
 - В Track тебе нужен контейнер Waypoints, в него добавляешь Waypoint
 - Waypoints.midlat и midlon -- среднее значение координат точек из Waypoints, которое при декодировании прибавляется к значениям Waypoint.lat и Waypoint.lon, используется для уменьшения размера данных. Если точка одна или размер тебя не заботит, можно оставить пустыми, это эквивалентно нулевым значениям, и тогда в Waypoint писать координаты без смещения

**Comment by wladich** [comment]
Поглощено #131
