### ISSUE TITLE
Все ссылки в leaflet-control-caption открываются в новых вкладах

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#171]
Видимо, это баг. Для протокола `mailto` и локальных ссылок (для якорей `#`) это не подходит.

Точнее, лучше открытие в новых вкладках переназначить на атрибут target.

**Comment by wladich** [comment]
Reportt problem ("#") была закомичена случайно, убрал
mailto добавил target

Для остальных -- это фича https://github.com/wladich/nakarte/blob/7e01a2fc74577a5f7a10f65b40770e9971f3cda2/public/index.html#L17

**Comment by myadzel** [comment]
Фича некорректная -- у меня запускается почтовая программа, и одновременно с этим открывается пустая вкладка в браузере для `mailto`.

**Comment by wladich** [comment]
mailto открывает новую вкладку даже после https://github.com/wladich/nakarte/commit/7e01a2fc74577a5f7a10f65b40770e9971f3cda2 ? Какой браузер? Хром перестал открывать.
