### ISSUE TITLE
slazav maps: change of object numbers

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#173]
По предложению O.Vlasenko в картах был переделан typ-файл и добавлены/изменены некоторые знаки. Самое существенное: поменялись все перевалы. С 6620-6626 на 6700-6706, из-за какой-то неведомой мне проблемы при создании img-файлов и показе их в gps.

Карты и mapsoft будут изменены, чтобы ничего не испортилось. Соответственно, надо будет как-то обновить сборку для nakarte.tk. 
Все изменения находятся в mapsoft/vector/data/styles.m4 и mapsoft/core/img_io/gobj_vmap.cpp
Проверю и закоммичу все в ближайшее время (с картами могу подождать, если надо).

**Comment by wladich** [comment]
Карты можно сразу, я их рендерю и выкладываю вручную. Когда будет новая версия, сделаю временный слой, чтобы я и ты могли проверить, что всё рендерится правильно.

**Comment by slazav** [comment]
все выложил!

**Comment by cornet1973** [comment]
Про перевалы небольшое уточнение. Проблема находится не в сборке IMG, а в сборке TYP. Номера 6620-6626 не могут быть корректно использованы в TYP - при сборке автоматически переназначаются на другие номера, какие именно - зависит от логики, прошитой в используемом компиляторе. Так или иначе, но получаем TYP содержащий какие то иные номера знаков перевалов нежели предполагаемые и используемые в IMG.
Соответственно, при сложении корректного IMG с таким не корректным TYP результирующая карта отображает перевалы не корректно.

**Comment by wladich** [comment]
Вижу коммит в map_hr. А map_podm будет как-то меняться?

**Comment by slazav** [comment]
Нет, перевалов там не должно быть, и никаких изменений не ожидается.

**Comment by cornet1973** [comment]
А как же новые знаки, вполне применимые к МО:
;POLYGON  0x0D пески - новый знак
;POLYGON  0x19 скалы - новый знак
;POI 0x2B03  хорошее место для стоянки
;POI 0x660A  одиночное дерево - ориентир
?

**Comment by slazav** [comment]
Сейчас на карте их нет, так что все будет показываться как прежде. Обновить mapsoft все равно надо из-за хребтовок, после этого и Подмосковье должно обновляться нормально с новыми знаками.

**Comment by wladich** [comment]
Собрал mapsoft, отрендерил карты новой версией.
Вроде всё в порядке:
https://nakarte.me/#m=13/55.89625/36.72215&l=O/Q/Z/-cseyJuYW1lIjoiU2xhemF2IG5ldyIsInVybCI6Imh0dHBzOi8vdGlsZXMubmFrYXJ0ZS5tZS9tYXBfcG9kbV9uZXcve3p9L3t4fS97eX0iLCJ0bXMiOnRydWUsInNjYWxlRGVwZW5kZW50IjpmYWxzZSwibWF4Wm9vbSI6MTQsImlzT3ZlcmxheSI6dHJ1ZSwiaXNUb3AiOnRydWV9/-cseyJuYW1lIjoic2xhemF2IG1vdW50YWlucyBuZXciLCJ1cmwiOiJodHRwczovL3RpbGVzLm5ha2FydGUubWUvbWFwX2hyX25ldy97en0ve3h9L3t5fSIsInRtcyI6dHJ1ZSwic2NhbGVEZXBlbmRlbnQiOmZhbHNlLCJtYXhab29tIjoxMywiaXNPdmVybGF5Ijp0cnVlLCJpc1RvcCI6dHJ1ZX0=
