### ISSUE TITLE
Перестали открываться треки по внешнему URL

### ISSUE THREAD

**Issue by ancrane** [wladich/nakarte#176]
Ввожу в поле Track URL адрес, а сайт пишет, что "Could not download file from url "http://velotrex.ru/files/1542886765_5bf6956ddff3c.xml", no data could be loaded"

Адрес корректный, открывается из браузера.

**Comment by wladich** [comment]
Откатил вчерашний коммит, заработало

**Comment by ancrane** [comment]
Да, точно. Спасибо.
