### ISSUE TITLE
ESLint config

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#183]
It's a good common practice to run ESLint before submitting a PR, but there is no project specific `.eslintrc.json` [config file](https://eslint.org/docs/user-guide/configuring) currently. Could you please add it?
Something like:
```bash
$ cat << EOF > .eslintrc.json
{
    "env": {
        "browser": true
    },
    "extends": "eslint:recommended",
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true
        },
        "sourceType": "module"
    },
    "rules": {
        "indent": ["error", 4],
        "linebreak-style": ["error", "unix"],
        "quotes": ["error", "single"],
        "semi": ["error", "always"]
    }
}
```

**Comment by wladich** [comment]
В [1] пишут, что конфиг может быть в package.json
В package.json конфиг есть (eslintConfig).
Не могу сказать, что он мне нравится, просто я его не менял с самого начала.
[1] https://eslint.org/docs/user-guide/configuring

**Comment by wladich** [comment]
Написал эпик, в т.ч. и про eslint: #186
