### ISSUE TITLE
[geocaching.su] HTML symbol entity instead of actual symbol

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#191]
`#257;` is being displayed instead of `ā`:
![screenshot_2018-12-03 nakarte me](https://user-images.githubusercontent.com/688044/49358595-45461f80-f6e4-11e8-8543-6a9096484fa3.png)
![screenshot_2018-12-03 suomen kielen paiva](https://user-images.githubusercontent.com/688044/49358597-45deb600-f6e4-11e8-9fee-e59d730c100e.png)

**Comment by wladich** [comment]
HTML-entity у них прямо в строках в kml, да ещё и с пробелами вокруг. 
Кроме того, у геокешиннга всё плохо -- после редизайна они сломали весь экспорт, на nakarte висит старая версия. Постараюсь не забыть им написать, может заодно и это пофиксят.

**Comment by sikmir** [comment]
> Кроме того, у геокешиннга всё плохо

Согласен, у них даже после сохранения коментария из сообщения пропадают все такие символы (типа ä, ö). Я им давно уже писал об этом, никакого ответа не получил.

**Comment by wladich** [comment]
на stage.nakarte.me вмест со всем 8 релизом

**Comment by sikmir** [comment]
Сейчас `ā` символы скипаются:
![scr0](https://user-images.githubusercontent.com/688044/176359086-00cd4559-4da9-4edf-abaa-c94ac223ac82.jpg)
Видим `piv` вместо `pāivā`.

**Comment by wladich** [comment]
Сейчас точки берутся из экспорта в wpt, в котором кодировка cp-1251 и все "лишние" символы удаляются.
Посмотрел, экспорт в "Текстовый файл (txt)" сейчас делается в utf-8 и сохраняет все символы.

**Comment by wladich** [comment]
Поправил
