### ISSUE TITLE
Кратчайшее расстояние между двумя точками

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#195]
Возьмем [трек из двух точек MSK и SF](https://nakarte.me/#m=3/47.51627/-42.42233&l=O&nktl=jSHRwp53vqGphF2V-JVR-A):
Длина ортодромии (great-circle): ~9448 км.
Длина локсодромии (rhumb line): ~12190 км.
На карте противоречие - нарисован локсодром, но километраж посчитан по ортодрому:
![screenshot_2018-12-13 nakarte me](https://user-images.githubusercontent.com/688044/49899751-a18c0a80-fe6d-11e8-98c5-a1dcf28d29c5.png)

**Comment by wladich** [comment]
Won't fix.
Измерения для запуска МБР за пределами основного назначения сайта. 
А на нормальных вело-пеше-водных масштабах разница не заметна.
