### ISSUE TITLE
Переименование ссылок "поделиться треками"

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#205]
Некоторые люди не понимают, что сервис может сохранять ссылку и треки (чтобы поделиться файлами). Даже те люди, которые часто им пользуются (ну, не нажимали они туда, думали это что-то иное, более техническое). 

Предлагаю переименовать "Copy all tracks to clipboard" (и аналогичные) на "Share link" или на что-то в этом духе.

**Comment by wladich** [comment]
Сейчас имеем:
1. "Copy link to clipboard" в контекстном меню трека
2. "Copy all tracks to clipboard" в меню контрола
3. "Copy visible tracks to clipboard" в меню контрола

**Comment by myadzel** [comment]
#240

**Comment by wladich** [comment]
> #240

Не понял

**Comment by myadzel** [comment]
> Не понял

Если править контекстные меню, заодно и это эту issue исправить (там тоже "copy to clipboard").

**Comment by wladich** [comment]
Так я и не привык с "Share link"
Будет "Copy link for track"

**Comment by myadzel** [comment]
Да. Спасибо!
