### ISSUE TITLE
Не импортируются путевые точки из маршрутов Movescount

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#213]
В #137 я забыл учесть этот момент.

Точки с индексами из объекта `data` это путевые точки. Их нужно включать в трек только в качестве `wpt`.

Пример трека с путевыми точками -- http://www.movescount.com/map?route=4216254.

```json
{"points":{"latitudes":[55.640437,55.640806,55.641175,55.641715,55.64293,55.643421],"longitudes":[37.553888,37.556071,37.558254,37.558192,37.55569,37.554444],"altitudes":[210.0,210.0,210.0,210.0,210.0,220.0],"data":{"1":{"name":"WP1","type":27},"2":{"name":"SECOND WPT","type":14},"4":{"name":"++","type":12}}},"waypointCount":3,"createdBy":1503629,"activityID":3,"routeName":"--wpt-test","routeDescription":"","tags":[],"id":4216254,"isPrivate":false,"distance":649,"location":"Москва, Московская область, Russia","latitude":55.6404370000,"longitude":37.5538880000,"isEditable":true,"thumbs":0,"timesUsed":0,"shouts":0,"usersCount":1,"ascent":10.0,"descent":0.0,"mapProviderName":"mapbox"}
```

**Comment by myadzel** [comment]
Возьму себе.

**Comment by myadzel** [comment]
Особенность редактора маршрута в Movescount -- путевые точки можно ставить только на нитке маршрута, несмотря на то, что спецификация GPX отделяет их от самого маршрута. 

Но тогда тут вопрос -- если парсер их не будет включать в маршрут, то итоговый трек будет не таким, как ожидает пользователь. Все-таки считаю, что нужно сохранять и как точки маршрута и отдельно дублировать в wpt.

@wladich, что думаешь?

**Comment by wladich** [comment]
У тестового трека сделай, пожалуйста имя с русскими буквами и добавь точку тоже с русскими буквами

**Comment by myadzel** [comment]
> имя с русскими буквами и добавь точку тоже с русскими буквами

Не позволяет Movescount использовать символы, кроме латинского алфавита.

**Comment by wladich** [comment]
Не совсем, можно ещё некоторые диакритические знаки
http://www.movescount.com/map?route=4492096&lat=49.54730250000003&lon=16.798074499999984&zoom=16&activity=3&style=suunto-dark
