### ISSUE TITLE
Счетчик для имён точек неубывающий, надо исправить

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#217]
Сценарий:
1. Создаём точку с именем "100500 abc"
2. Удаляем её
3. Создаём новую точку -- новый номер 100501.

Не надо хранить глобальный счетчик, начальный номер точки должен вычислятся как максимальный номер среди существующих + 1

**Comment by myadzel** [comment]
Поправил именование.

**Comment by myadzel** [comment]
Еще проблема -- маркер не всегда успевает отрисоваться до prompt. Иногда вообще точек не видно, браузерный repaint не успевает отработать, увеличение времени в таймауте тоже не помогает, все-таки там callback нужен.

Следующий код не работает, как ожидается:

```js
// we need to show prompt after marker is dispalyed;
// grid layer is updated in setTimout(..., 0)after adding marker
// it is better to do it on 'load' event but when it is fired marker is not yet displayed
setTimeout(() => {
    this.renamePoint(marker);
    this.beginPointCreate(parentTrack);
}, 10);
```

**Comment by wladich** [comment]
Да, такая проблема есть, вынеси, пожалуйста, в отдельный issue.
