### ISSUE TITLE
True azimuth / Magnetic azimuth 

### ISSUE THREAD

**Issue by kosorotov** [wladich/nakarte#219]
Для направления на север в Москве сейчас выводится:
True azimuth: 0
Magnetic azimuth: 349, который согласно калькулятора https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml должен быть равен 11 градусам

**Comment by wladich** [comment]
По указанной ссылке показывается Declination - склонение, а не "магнитный азимут направления на север".  Если к картинке приложить компас так, чтобы верхняя стрелка картинки совпала с буквой С на компасе, то направление на истинный север как раз совпадёт с цифрой 349 на шкале компаса. Если, конечно, компас обычный туристический, а не горный.
