### ISSUE TITLE
Feature:Аналитика для схем Цветкова

### ISSUE THREAD

**Issue by Xeenych** [wladich/nakarte#221]
Нельзя ли все-таки как-нибудь прикрутить гугл и яндекс аналитику при выборе слоя с моей схемой?

Может, какой-нибудь Iframe подгружать с map.gutka.ru или еще как-то?

**Comment by wladich** [comment]
Скрытый iframe на сторонний сайт я точно не хочу  по соображениям безопасности.
Я согласен добавить дёрганье какого-нибудь урл-а, если у этих аналитик есть такая возможность.
И желательно сделать PR

**Comment by Xeenych** [comment]
А что такое PR?
