### ISSUE TITLE
npm run build - неправильные пути

### ISSUE THREAD

**Issue by Xeenych** [wladich/nakarte#222]
скачал проект, сделал npm install, npm run build
В папке build появились index.html и папка static

В index.html все пути вида: "/static/css/main.2c80795f.css", а браузер пытается загрузить файлы по пути "/D:/static/css/vendor.86456fe6.css"
А должно быть, видимо,  с точкой "./static/css/main.2c80795f.css"

**Comment by myadzel** [comment]
Если вы не умеете работать с запуском приложения на Node.JS, а запускаете сборку проекта и пытаетесь открыть ее вне окружения веб-сервера, то мне кажется, что нет смысла плодить такие issue, а уж тем более браться за написание скриптов в нем.

**Comment by wladich** [comment]
Всё не так страшно. 
npm run build собирает бандл для раздачи веб-сервеом. 
Для разработки это не нужно запускать npm start -- он соберёт проект, запустит веб-сервер и скорее всего откроет браузер (иногда не открывает...)

**Comment by Xeenych** [comment]
Нет, не умею.
Во-первых мне бандл и нужен.
Во-вторых npm start, конечно, запускает сервер и раздает index.html, но ничего не работает. Веб-страница - чистый лист и куча ошибок в консоли хрома.

**Comment by myadzel** [comment]
Скорее всего, вы выложили сборку не в корень веб-сервера или пытаетесь открыть индексный файл локально.

В вашем случае вам поможет добавление в файл `config.json` параметра `homepage` с указанием "текущей директории" (`./`) для определения "правильных" путей в итоговой сборке проекта:

`"homepage": "./"`

**Comment by myadzel** [comment]
@Xeenych, ну что, получилось?

**Comment by Xeenych** [comment]
@myadzel нет, не получается.
Файл config.json есть только в node_modules\table\dist\schemas\, но думаю, это не то, что надо.

есть src\config.js
Кстати, в нем, лишняя запятая в конце:   `tracksStorageServer: 'https://tracks.nakarte.me',`

**Comment by myadzel** [comment]
Простите, package.json, конечно же :-)

Попробуйте и отпишите.

**Comment by myadzel** [comment]
> Кстати, в нем, лишняя запятая в конце (если я правильно читаю жаваскрипт): `tracksStorageServer: 'https://tracks.nakarte.me',`

С запятой там все в порядке:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by Xeenych** [comment]
Да, теперь пути в получившемся index.html относительные и правильные

Однако, при открытии index.html страница пустая.
В консоле ошибка

```
Uncaught TypeError: Cannot set property 'JSUnzip' of undefined
    at vendor.d040da52.js:6
    at Object.<anonymous> (vendor.d040da52.js:6)
    at e (vendor.d040da52.js:1)
    at Object.<anonymous> (main.429f34aa.js:10)
    at e (vendor.d040da52.js:1)
    at Object.<anonymous> (main.429f34aa.js:10)
    at e (vendor.d040da52.js:1)
    at Object.<anonymous> (main.429f34aa.js:2)
    at e (vendor.d040da52.js:1)
    at Object.<anonymous> (main.429f34aa.js:1)
```

**Comment by myadzel** [comment]
#207

**Comment by wladich** [comment]
конфиг полностью переделан, проблема должна уйти

**Comment by OSova2023** [comment]
> Скорее всего, вы выложили сборку не в корень веб-сервера или пытаетесь открыть индексный файл локально.
> 
> В вашем случае вам поможет добавление в файл `config.json` параметра `homepage` с указанием "текущей директории" (`./`) для определения "правильных" путей в итоговой сборке проекта:
> 
> `"homepage": "./"`
МНЕ ПОМОГЛО ПОНЯТЬ ОШИБКУ. СПАСИБО!
