### ISSUE TITLE
Гулгопанорамы перешли в режим "For development purposes only"

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#227]

**Comment by myadzel** [comment]
Гугл-карты показывают кастомный алерт, текст для "For developer purposes only" и инверсируют canvas.

Попробовал поиграться со стилями. Если инверсировать изображение в стилях, то они делают его черным, т. е. где-то высчитывают и прячут, если нет фильтра. Но это обходится добавлением инверсии родительскому элементу :-)

Также с текстом поработал -- если текст "For developer purposes only" спрятать через display, то это не cработает, тоже где-то проверки свойств, а вот `font-size: 0` сработал.

Алерт просто прячется через `z-index: -1` :-) 

Пока вроде работает.
