### ISSUE TITLE
не сохраняется PDF для карт Финляндии

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#232]
При попытке сохранить такую карту вылезает ошибка "Failed to create PDF: network error":
https://nakarte.me/#m=11/60.15706/24.97810&l=Fmk&p=500/300/auto/210/297/3/3/3/3/60.19274/24.91837/0/0

**Comment by wladich** [comment]
Они зачем-то в ответах дублируют заголовок Access-Control-Allow-Origin. А браузеры считают, что так делать нельзя и игнорируют их. Надо бы хозяевам сайта написать...

**Comment by slazav** [comment]
что-то пока не исправилось

**Comment by slazav** [comment]
Спасибо! Сейчас работает.
