### ISSUE TITLE
не работают карты Great Britain Topo

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#233]
Кажется, какая-то проблема в диалоге выбора слоев: при добавлении этой карты в список возникает неактивный checkbox.

**Comment by wladich** [comment]
Эти карты есть только с 12 уровня. Если указать этот уровень как минимальный, leaflet на более высоких уровнях делает чекбокс неактивным, зачем-то там так сделано.

**Comment by slazav** [comment]
Точно, я даже уже натыкался на это, но забыл...
