### ISSUE TITLE
Отличия трека в отображении и высотном профиле

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#247]
Прислали ссылку https://nakarte.me/#m=12/55.33578/38.86293&l=O&nktl=bvkNApUbmV6YnvBzkQrKiw отображается как 69,9 км, а в высотном профиле, как 79,7 км. Склеили в редакторе, вышло так странно...

Открыл трек в текстовом редакторе -- там первая последовательность из точки, но визуально она вообще никак не отображается (там две одинаковые почему-то, но не суть, такая же проблема будет и с одной точкой в сегменте). 

Если (обычно) в редакторе не завершить редактирование (поставить метку, потом нажать Esc и кликнуть в стороне), то он удаляет сам этот "несостоявшийся" трек. 

Здесь же ситуация такая, что никак эта точка не маркируется и, соответственно, не редактируется, но общую картину портит -- так как трек уже через сайт не исправить (не виден первый сегмент).

**Comment by wladich** [comment]
1. Разная длина это нормально, так всегда происходит, когда трек состоит из нескольких сегментов, которые не стыкуются друг с другом, где-то это даже обсуждалось.
2. Объявим, что треки из 1 точки или двух совпадающих, полученные из внешнего источника это нормально.
3. Фикс для двух точек:
    * в стиле полилинии поменять lineCap с butt на round. Заодно станут слегка заметны границы между стыкующимися сегментами.
    * при печати тоже поменять стиль. Здесь подсветка границ не нужна, хорошо бы сделать изменение стиля только для подобных вырожденных сегментов.
4. Т.к. svg-полилинии из 1 точки не отображаются, то при создании сегмента из объекта geodata будем их чинить -- превращать в две.

**Comment by wladich** [comment]
пофиксил
