### ISSUE TITLE
Импорт файла с несколькими треками

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#248]
Сегодня GPSies сообщил, что их выкупает AllTrail, поэтому я решил скачать все свои треки оттуда, но он создает в экспорте один GPX-файл, в котором много узлов tkr. При импорте nakarte преобразует их в trkseg, что, имхо, не совсем корректно -- мы теряем треки, названия треков и оригинальные trkseg в них.

Возможно, стоит сделать диалоговое окно при импорте такого трека (с множеством trk), с предложением объединить в один трек с последовательностями, либо импортировать с разбиением на треки (что предпочтительнее).

**Comment by wladich** [comment]
Изначально было сделано так, потому что навигаторы Garmin делали gpx-файлы с множеством треков с именами типа "ACTIVE LOG XXXXX". 
Описанное поведение GPSies, как мне кажется, является мало распространенным. Для разовой задачи делать фичу не надо.
