### ISSUE TITLE
Не открываются ссылки на geocaching/wikimapia

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#249]
После последних обновлений Firefox, перестали открываться ссылки на geocaching и wikimapia. Вместо этого в новом окне выдает "404 Not Found". В Chromium/Opera все по прежнему работает.

**Comment by tarwirdur** [comment]
Проблему не воспроизвожу на 69.0 (Linux64). 69.0 вышел 03.09, 69.1 - 18.09, но у меня его пока нет в репозиториях.

В changelog не вижу никаких значимых изменений: https://www.mozilla.org/en-US/firefox/69.0.1/releasenotes/

**Comment by sikmir** [comment]
У меня как раз 69.0 (Linux64).

**Comment by tarwirdur** [comment]
> Вместо этого в новом окне выдает "404 Not Found".

А url в строке адресной строке какой?

**Comment by sikmir** [comment]
> А url в строке адресной строке какой?

Например такой:
`https://nakarte.me/r/?url=https%3A%2F%2Fgeocaching.su%2F%3Fpn%3D101%26cid%3D23566&event=a4mwyk7ww4o`

**Comment by sikmir** [comment]
Несколько дней назад у nakarte.me была какая-то проблема с ssl сертификатом, по крайней мере статус в firefox был не зеленый, я думал с этим как-то связано. Но теперь ssl сертификат норм, а проблема с ссылками осталась.

**Comment by tarwirdur** [comment]
А не стоит ли у тебя плагин https-everywhere?

см. https://github.com/wladich/nakarte/blob/master/src/lib/popup-window/index.js#L25

Там ссылка идет на http://nakarte.me/r/... А у тебя в url - https.
но то что на https не идет правильный редирект - явно ошибка.

**Comment by sikmir** [comment]
> А не стоит ли у тебя плагин https-everywhere?

Не стоит, и до апдейта все работало, может в Firefox включили по дефолту http->https?

**Comment by tarwirdur** [comment]
Странно. Возможно HSTS политика может оказать такое влияние. У меня флага для nakarte.me там нет. Посмотри:

`cat ~/.mozilla/firefox/*.default/SiteSecurityServiceState.txt | grep nakarte`

**Comment by sikmir** [comment]
Для чистоты эксперимента, проверил на macOS Firefox 69.0, то же самое, то есть проблема с дефольтными настройками.

**Comment by sikmir** [comment]
> cat ~/.mozilla/firefox/*.default/SiteSecurityServiceState.txt | grep nakarte

`proxy.nakarte.me:HSTS	3	17980	1574681299799,1,1,2`

**Comment by tarwirdur** [comment]
У меня больше нет идей.

И не понятно откуда взялась hsts запись для `proxy.nakarte.me`.

> Для чистоты эксперимента, проверил на macOS Firefox 69.0, то же самое, то есть проблема с дефолтными настройками.

Но у меня то тоже ff69 :)

___

в любом случае надо починить конфигурацию веб сервера для корректного редиректа с https://nakrte.me/r/... И, возможно, в коде изменить http на https в ссылке. (или просто "//nakarte.me/r/...")

**Comment by myadzel** [comment]
По-моему, все очевидно.

Для https на сервере nakarte не настроен обработчик URL для редиректа `/r`:

https://nakarte.me/r/?url=/ выдает 404-ю) а с http://nakarte.me/r/?url=/ корректно редиректит на главную.

**Comment by sikmir** [comment]
> По-моему, все очевидно.

Это то понятно, не понятно почему Firefox начал принудительно менять http на https и откуда та hsts запись.

**Comment by wladich** [comment]
Спасибо за сообщение. Всё правильно, в коде редирект был через http://nakarte/r, а в конфиге nginx не было обработки /r для https.
Поправил конфиг и код, прошу @sikmir  проверить в нужном firefox на https://stage.nakarte.me И над https://nakarte.me (у меня 69.0 работает без правки).

**Comment by sikmir** [comment]
Да, теперь все работает. Спасибо!

**Comment by wladich** [comment]
Про проблемы с ssl-сертификатом -- очень странно, сертификат последний раз обновлялся 1 сентября...
Про HSTS на proxy.nakarte.me -- скорее всего прилетел заголовок от одного из проксируемых сайтов. Наверное, надо фильтровать в конфиге nginx...
