### ISSUE TITLE
Загрузка треков с Trace de Trail 

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#250]
Так как Trace de Trail официально используется ITRA, то было бы неплохо загружать треки оттуда, так ка сейчас можно скачивать GPX-треки только после регистрации (и входа) на сервис, что очень неудобно.

**Comment by sikmir** [comment]
> ...так ка сейчас можно скачивать GPX-треки только после регистрации (и входа) на сервис, что очень неудобно.

Кстати, а воможно ли как-то сделать, чтобы если вход на сайт выполнен, то nakarte мог бы открыть трек по ссылке? Как понимаю там какие-то шаманства с куками нужны. Такая проблема не только с Trace de Trail, но и с Wikiloc.

**Comment by myadzel** [comment]
Я pull-реквест добавил, он теперь и приватные треки может импортировать)

Там не шаманство, просто домен и язык должны совпадать с авторизационными, чтобы скачать руками с Trace de Trail, это тоже очень напрягает.
