### ISSUE TITLE
Загрузка треков из Wikiloc

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#252]
https://www.wikiloc.com/
Скачивание треков доступно только залогиненым пользователям.

**Comment by wladich** [comment]
Трек передаётся в html.
Формат трека: https://github.com/TWKB/Specification/blob/master/twkb.md

**Comment by sikmir** [comment]
```js
<script>
	...
  var mapData={"mapData":[{"spaId":...,"nom":"<name>", ...,"geom":"<twkb-serialized track>", ...}]};
  ...
</script>
```
