### ISSUE TITLE
Для фоток wikimedia добавить фильтрацию ответа по mime-type + обрабатывать страницы без координат

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#253]
Проблема: при клике на фиолетовой точке покрытия wikimedia иногда не открывается окно просмотра фотографий.

Тестовая точка: https://nakarte.me/#m=13/26.35311/17.26278&l=O&n2=_w&nktl=3JNW2XrHhhcgh87WMWFNXA

При запросе панорам (https://commons.wikimedia.org/w/api.php?origin=*&format=json&action=query&generator=geosearch&ggsprimary=all&ggsnamespace=6&ggslimit=10&iilimit=1&coprimary=all&ggsradius=420.5525449422481&ggscoord=26.338345337108986|17.268276214599613&iiurlwidth=134&prop=imageinfo|coordinates&iiprop=url|mime|size|extmetadata|commonmetadata|metadata) приходит ответ: https://gist.github.com/wladich/0fe0b6632ec4c471ef5f446d1e41d04f.

В нём кроме jpeg-а есть два svg. Их показывать не надо, т.к. это не фотографии. 

Вторая проблема - у svg почему-то отсутствуют координаты в ответе API. Скорее всего, это очередной баг в викимедии, изучать его мне неохота. Надеюсь, он только для svg. Но мы из-за этого падаем и не показываем даже хорошую фотографию с координатами.

Что надо сделать:
1. Показывать фотографии, для которых в ответе API нет координат, При этом не подсвечиваем точное место, а указатель ставим на точку клика.
2. В этом случае слать на sentry сообщение об ошибке, чтобы отловить очередной снос координат из базы викимедии.
3. Показывать файлы только с типом image/jpeg (есть в ответе API). Посмотреть, может видео тоже будет работать.

Примечание: для карты покрытия файлы отбираются по условию `ext.lower() == 'jpg'`

**Comment by myadzel** [comment]
Пример JPEG без координат:

`curl 'https://commons.wikimedia.org/w/api.php?origin=*&format=json&action=query&generator=geosearch&ggsprimary=all&ggsnamespace=6&ggslimit=10&iilimit=1&coprimary=all&ggsradius=158.7904785421645&ggscoord=49.489649981917516|21.28360748291016&iiurlwidth=134&prop=imageinfo|coordinates&iiprop=url|mime|size|extmetadata|commonmetadata|metadata' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://nakarte.me/' -H 'Origin: https://nakarte.me' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' --compressed`

**Comment by wladich** [comment]
Уже починили на стороне викимедии. Первый пример перестал присылать svg и в обоих примерах теперь есть координаты.

**Comment by wladich** [comment]
Вот новое: https://commons.wikimedia.org/w/api.php?origin=*&format=json&action=query&generator=geosearch&ggsprimary=all&ggsnamespace=6&ggslimit=10&iilimit=1&coprimary=all&ggsradius=49.290369769880144&ggscoord=46.675325025412334|25.372109413146973&iiurlwidth=134%E2%80%A6

**Comment by wladich** [comment]
И ещё с несколькими страницами в ответе: https://commons.wikimedia.org/w/api.php?origin=*&format=json&action=query&generator=geosearch&ggsprimary=all&ggsnamespace=6&ggslimit=10&iilimit=1&coprimary=all&ggsradius=2396.6414385245885&ggscoord=49.36627773550062|19.822082519531254&iiurlwidth=134&prop=imageinfo|coordinates&iiprop=url|mime|size|extmetadata|commonmetadata|metadata

**Comment by wladich** [comment]
Обработка страниц без координат оказалась нетривиальной. Если вместо отсутствующих координат подставлять координаты клика, то а) усложняется обработка кластеров точек, б) не работает загрузка состояния из адресной строки. Также подобные фотографии отсутствуют в карте покрытия, так что пользователь может только случайно попасть в неё на мелком зуме.
Так что будем просто пропускать фотографии без координат.

Отправил баг репорт в викимедию: https://phabricator.wikimedia.org/T235000
