### ISSUE TITLE
Не отображаются некоторые фотографии с Google

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#254]
Точка есть, но в ответе API -- `Search returned no images`.

https://nakarte.me/#m=16/55.05229/38.06953&l=O&n2=_g&nktl=qwovfiDysffiqObSXrWnQw

**Comment by wladich** [comment]
Проблема на стороне гугла: https://www.google.com/maps/place/55%C2%B003'08.2%22N+38%C2%B004'10.3%22E/@55.0521855,38.0678678,17z/data=!4m5!3m4!1s0x0:0x0!8m2!3d55.05229!4d38.06952

тоже самое, точка есть, панорамы нет

**Comment by myadzel** [comment]
Пользователи ведь не знают, баг это Google или сервиса. Может стоит хотя бы сообщение выводить, типа "Ошибка загрузки фотографии с сервиса Google"?

**Comment by wladich** [comment]
Для нас это ничем не отличается от клика в белое поле, где нет покрытия. Чтобы не показывать лишние сообщения придётся анализировать гугловские тайлы, чего делать совершенно неохота. Пользователи, если и страдают, то не сильно -- это первое сообщение, хотя проблему я наблюдаю довольно давно и регулярно.
