### ISSUE TITLE
Пополнение слоя Races

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#256]
У меня (думаю, не только у меня) постепенно накапливаются привязанные карты разных гонок. В частности, по Эстонии, Финляндии. Имеет ли смысл добавить их в слой Races? Как их лучше выдать?

**Comment by wladich** [comment]
У меня довольно плохо с энтузиазмом, так что если тебе интересно добавлять карты, особенно регулярно, то лучше всего забрать эту часть работы себе. У меня имеются более-менее структурированные коллекции карт ориентирования и гонок, плюс кое-какие утилиты для управления и привязки. Если интересно - пиши на почту или в телеграм.

**Comment by myadzel** [comment]
Есть предложение "из народа" -- дополнять карты названием и годом мероприятия.

**Comment by sikmir** [comment]
> Есть предложение "из народа" -- дополнять карты названием и годом мероприятия.

Оно же уже есть, по крайней мере на слое Races.

**Comment by myadzel** [comment]
> > Есть предложение "из народа" -- дополнять карты названием и годом мероприятия.
> 
> Оно же уже есть, по крайней мере на слое Races.

Далеко не на всех картах.

**Comment by wladich** [comment]
Нашел отсутствующую подпись только для Жаркого июля 2018 года, поправил.
Где ещё есть?

**Comment by myadzel** [comment]
https://nakarte.me/#m=15/56.57185/34.99192&l=O/U&nktl=jevuOqC1bAbuG76dYJmSGg

**Comment by wladich** [comment]
Это карта из пачки опубликованных на https://x-race.info/items/68804/

У меня есть только название файла "Чукавино Тверск обл 100 2013.ocd". Для всех остальных название заполнено, если ещё гед-то не отображается, надо смотреть.

**Comment by wladich** [comment]
Тема, кажется, протухла, закрываю

**Comment by myadzel** [comment]
https://nakarte.me/#m=14/54.86228/37.89953&l=O/R&nktl=DYHlTf7juiJ_d2lje6QLqA

**Comment by wladich** [comment]
Это o-sport, там все или почти все карты без названий.
В Races обычно карта делается специально под событие, поэтому название соревнований более-менее характеризует карту.

В спорториентировании карта обычно используется много раз, поэтому писать что-то вроде "Москомпас, этап 34" мне кажется бессмысленным.

**Comment by sikmir** [comment]
> У меня имеются более-менее структурированные коллекции карт ориентирования и гонок, плюс кое-какие утилиты для управления и привязки. Если интересно - пиши на почту или в телеграм.

@wladich а можно поподробнее про процесс добавления карт в Races? Например очень бы хотелось увидеть в слое карту последнего ОМБ (https://kandid.ru/maps20/omb20.jpg), можно как-то посодействовать этому? Может сделать этот процесс как-то более открытым, через PR например?

**Comment by wladich** [comment]
Если конкретно одну эту карту, то может в декабре займусь - у меня отпуск, а ехать некуда...

Если есть большое желание поучаствовать (в т.ч. написанием софта) в поддержке слоёв o-sport и races или просто узнать как оно сейчас делается - напиши в почту или телеграм.

**Comment by 2813** [comment]
Тоже интересно привязать карту спорт-ориентирования и рогейна для своей "деревни". 
Интересуюсь алгоритмом. Куда нить выложена инструкция или все так же стучаться по личкам?

**Comment by wladich** [comment]
@2813

Инструкции как добавить одну-две карты нет и не предвидится. Вы можете прислать имеющиеся карты на адрес nakarte@nakarte.me, я постараюсь добавить их в обозримом будущем.

**Comment by sikmir** [comment]
> Вы можете прислать имеющиеся карты на адрес [nakarte@nakarte.me](mailto:nakarte@nakarte.me), я постараюсь добавить их в обозримом будущем.

* ВМБ 2019 - https://kandid.ru/maps19/vmb19.jpg
* ВМБ 2021 - https://kandid.ru/maps21/vmb21_1.jpg, https://kandid.ru/maps21/vmb21_2.jpg
