### ISSUE TITLE
[FEATURE REQUEST] Сохранение куска карты в pdf по ссылке

### ISSUE THREAD

**Issue by Xeenych** [wladich/nakarte#260]
Можно ли сделать такую ссылку, чтобы при переходе по ней скачивался pdf с одним или несколькими листами карты?

что-то типа такого, но чтобы pdf сразу начинал скачиваться
https://nakarte.me/#m=12/41.93638/77.54768&l=O/Mt/Wp&p=500/300/15/210/297/3/3/3/3/41.93166/77.56554/0/41.93140/77.43542/0/0

**Comment by wladich** [comment]
А для чего? Если нужно передать файл так, чтобы получателю не надо было ничего объяснять, не лучше ли использовать файлообменник, например яндекс диск или transfer.sh?

**Comment by Xeenych** [comment]
На файлообменнике карта будет устаревать, а по ссылке каждый раз будет скачиваться актуальная версия.

**Comment by slazav** [comment]
Это, наверное, не только про устаревание, но и про количество операций, которые нужно совершить, чтобы передать карту. Но, мне кажется, что приведенная выше ссылка вполне удобно решает эту задачу. А создавать ссылку, которая запускает какие-то тяжелые вычисления на компьютере ничего не подозревающего получателя - довольно сомнительно.

**Comment by wladich** [comment]
Я могу ошибаться, но предположу, что идея @Xeenych в том, чтобы опубликовать  ссылки для печати регулярно обновляющейся хребтовки. 
Для данной задачи, как мне кажется, лучше при обновлении карты в дополнение к тайлам генерировать ещё и растры для печати.

**Comment by Xeenych** [comment]
Да, все так. Думаю, я смогу генерировать фрагменты популярных районов для печати. Можно закрыть этот feature request.
