### ISSUE TITLE
Перетаскивание области для JNX

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#261]
Добавить перетаскивание области мышью.

**Comment by wladich** [comment]
А зачем? Я вот обычно думаю про каждую отдельную сторону, где она должна быть.

**Comment by myadzel** [comment]
Не очень удобно изменять позицию. Возможность перетаскивания важна, имхо.

**Comment by wladich** [comment]
Если сделать, будет неприятный эффект, который сейчас можно наблюдать при добавлении листов для печати: если зазумиться так, что не видны границы области, то при попытке перемещения карты будет перемещаться область выделения, т.е. визуально ничего не будет происходить. На мой взгляд, это превосходит полезный эффект от возможности перетаскивания.
