### ISSUE TITLE
Ошибка в округлении координат

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#307]
Заметил, что в запросах к серверу высот ошибка -- широта округляется до 6 символов после точки, а долгота до 5.

**Comment by myadzel** [comment]
Также в других местах тоже есть округление до 5, имхо, здесь лучше тоже до 6 увеличить. И вынести в константу. Отдельной issue можно сделать.

**Comment by wladich** [comment]
В мастере, выкачу попозже
