### ISSUE TITLE
JSON с Вестры

### ISSUE THREAD

**Issue by Xeenych** [wladich/nakarte#344]
Титов сделал выгрузку перевалов в JSON
http://westra.ru/passes/kml/passes.php?&type=json&BBOX=86.0798582,49.755375,86.10714,49.765133

**Comment by wladich** [comment]
А в чём суть идеи/предложения?

**Comment by Xeenych** [comment]
Убрать прокси и забирать данные сразу с westra.ru

**Comment by wladich** [comment]
Единственный плюс использования api вестры напрямую - постепенная подгрузка данных, что уменьшит время первого показа слоя.
Но сейчас у меня реализована только загрузка всех перевалов сразу, загрузки тайлами нет. Сделать подгрузку тайлами с сохранением алгоритма расстановки подписей - задача не тривиальная, требует времени и не факт, что справлюсь.

Если же грузить из API сразу всё, то плюсов нет, одни минусы:

- больше объём данных (у меня данные перепаковываются, ненужное выкидывается)
- логику валидации и преобразования данных из скрипта надо переносить на клиент (время, баги)
- Владельцы сервера, скорее всего, не обрадуются повысившейся нагрузке
- дополнительная точка отказа.
