### ISSUE TITLE
Некрасиво обрабатываются ошибки загрузки tracedetrail

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#349]
Трек был удален или скрыт: https://tracedetrail.com/en/trace/trace/95201
При попытке загрузки получаем: "File "Tracedetrail track 95201" has unsupported format or is badly corrupt, no data could be loaded"

Должно быть сообщение, что трек не существует или скрыт.

@myadzel, посмотришь?

**Comment by myadzel** [comment]
Да. Скрытый трек они отдадут таким образом, а вот для несуществующего почему-то не отправляют статус 500, упорно шлют 200. 

Исправлю.
