### ISSUE TITLE
Задваиваются значения расстояний соседних точек

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#361]
Если последняя и предпоследняя точна находятся на небольшом расстоянии, то получается наложение значений их длины на высоких зумах. 

Пример:
https://nakarte.me/#m=18/55.69816/37.55122&l=G&nktl=_NRbn5ux3y-klscqbFvPdQ

Может в таком случае не стоит отображать расстояние на предпоследней точке?

**Comment by wladich** [comment]
Здесь две проблемы:
1. Наложение близко расположеных подписей на любом зуме.
2. Два одинаковых значения на высоких зумах.

П.1. специально обрабатывается, но неправильно, т.е. бага.

**Comment by wladich** [comment]
#364 не решает собственно проблему из п.2, но она теперь не проявляется, т.к. предпоследний отсчет теперь удаляется, если расположен близко к концу трека.
Проблема 1 (но не 2. и 3.) появится снова, если увеличить максимальный зум больше 18.

**Comment by wladich** [comment]
@myadzel 
#364 выложен на https://stage.nakarte.me. Посмотри, пожалуйста, если всё ok, то мержу.

**Comment by myadzel** [comment]
Да, сейчас OK.
