### ISSUE TITLE
Добавить возможность ручного ввода координат

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#382]
Несколько знакомых просят такой функционал. Через браузерную строку не очень удобно это делать, да и не все знают о такой скрытой возможности.

**Comment by myadzel** [comment]
Также, есть предложение увеличить точность с 5 до 6 знаков после точки (для единообразия). 

https://github.com/wladich/nakarte/issues/307

**Comment by wladich** [comment]
@myadzel 
Поиск с координатами решает исходную проблему?

**Comment by myadzel** [comment]
Да, конечно.

**Comment by slazav** [comment]
Да, спасибо! То, чего мне не хватало.
