### ISSUE TITLE
Добавить возможность использования нестандартной CRS для слоев

### ISSUE THREAD

**Issue by anisart** [wladich/nakarte#384]
Чтобы можно было использовать, например, слои Яндекса, которые не представлены в стандартном наборе. Например, просто галкой EPSG:3395.

**Comment by wladich** [comment]
Скажи пожалуйста, какие есть ещё полезные слои у Яндекса кроме треков?

**Comment by anisart** [comment]
Слои с GPS данными. Я использую https://core-gpstiles.maps.yandex.net/tiles?style=point&x={x}&y={y}&z={z}
Есть еще style=red_combined со стрелками направления движения, но он менее интересен для планирования.
Но эту же проекцию используют, например, Космоснимки. В том же OsmAnd эта галка есть - Элиптическая проекция Меркатора.

**Comment by wladich** [comment]
Посмотрел на треки яндекса - местами они есть в лесах там, где нет стравы, т.е. польза в них есть. Думаю, можно добавить как обычный слой в раздeл Routes and traces.

Соотв., #385 предлагаю закрыть.

**Comment by wladich** [comment]
добавил в #416, выложил на stage.nakarte.me

**Comment by wladich** [comment]
Заменено #416
