### ISSUE TITLE
GPX треки не открываются в BaseCamp и Mapsource

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#386]
Сообщение от пользователя:
> Трек с высотами из Nakarte.me не читается ни в BaseCamp, ни в MapSource. А BaseCamp прекращает работу в результате какой-то ошибки при открытии высотного графика скаченного с Nakarte.me БЕЗ высот (правок кнопкой на трек -> Открыть)

**Comment by myadzel** [comment]
Хм, ПО от Garmin, которое так и не научилось читать валидные GPX-файлы, что-то мне это напоминает.

**Comment by myadzel** [comment]
Предполагаю, что они везде хотят видеть узел ele с нулевой высотой.

**Comment by wladich** [comment]
Это именно сообщение, надо его сначала проверить, я не знаю, так ли это на самом деле, какие версии програм и сколько вирусов у пользователя на компьютере.

**Comment by myadzel** [comment]
OK. Поставлю на iMac на днях и протестирую.

**Comment by wladich** [comment]
Там ещё в #321 JNX не загружаются, если будешь ставить, проверь пожалуйста и это заодно.

**Comment by myadzel** [comment]
Установил BC, да, реально не загружает, ругается. Разобрался, в чем дело: какой-то умный дядя, решивший сэкономить на парсинге, обернул дочерние узлы в <xsd:sequence>, что вообще довольно странно, схема говорит, что <ele> первым должен быть, затем <time>. Поменял, работает. Сделать пул-реквест или просто поправишь сам?

**Comment by wladich** [comment]
Я чего-то не совсем понял, как должно быть. Можешь скинуть минимальный вариант, который оно читает?

**Comment by wladich** [comment]
Спасибо за замечание про схему. Я только что поправил и выложил, теперь gpx проходит валидацию. Можешь посмотреть, в таком виде тоже не грузится?

**Comment by myadzel** [comment]
Теперь загружаются нормально.
