### ISSUE TITLE
Прошу ответить на вопрос

### ISSUE THREAD

**Issue by yuri25** [wladich/nakarte#388]
Я извиняюсь, что задаю вопрос в issue... обычные сайты я могу создавать. Подскажите пожалуйста можно ли развернуть такой сервис на своем сайте или это нереально? Если можно поподробнее пожалуйста. Просто я увидел исходный код здесь и типа можно установить для локальной разработки...

**Comment by tarwirdur** [comment]
Можно использовать iframe. Посмотри https://github.com/wladich/nakarte/issues/132#issuecomment-423509460

> Подскажите пожалуйста можно ли развернуть такой сервис на своем сайте или это нереально? Если можно поподробнее пожалуйста. Просто я увидел исходный код здесь и типа можно установить для локальной разработки...

Задача непонятна.

**Comment by wladich** [comment]
Запустить копию интерфейса вполне реально, я знаю несколько успешных примеров.
Нужно:
1. Поправить config.js под свои нужды
2. Скопировать secrets.js.template в secrets.js и заполнить своими ключами по мере необходимости.
3. сделать `yarn; yarn run build`
4. Залить содержимое директории build на сервер из просто раздавать как статику.

Сложности возникнут когда/если вы захотите поднять собственные копии сервисов: сервис высот, треков, карт и т.д.

Но как правильно заметил предыдущий оратор, возможно вам будет достаточно встроить nakarte в свой сайт в виде iframe. Обычно свои версии сайта поднимают, когда хотят добавить какие-нибудь карты, которые я не соглашаюсь добавлять в основную версию.

Хорошо бы это описание сделать более подробным и добавить в readme...

**Comment by sikmir** [comment]
У меня как раз запущена своя копия nakarte в docker, изменения доступны в форке. Сейчас в коде есть места где еще захардкожено nakarte.me, например в телеметрии и еще где-то. Для mbtiles карт прекрасно работает [mbtileserver](https://github.com/consbio/mbtileserver). Сервис треков [tracks_storage_server](https://github.com/wladich/tracks_storage_server) тоже удалось поднять, пока еще не завернул в docker. Вообщем описание было бы очень полезным.
