### ISSUE TITLE
Failed to create JNX

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#4]
### Steps to reproduce
1. Open [nakarte.tk mapview](http://nakarte.tk/#m=9/66.36174/63.25378&l=E/N/J/F/K/W/Wp/-cseyJuYW1lIjoiT3BlblJhaWx3YXlNYXAiLCJ1cmwiOiJodHRwOi8ve3N9LnRpbGVzLm9wZW5yYWlsd2F5bWFwLm9yZy9zdGFuZGFyZC97en0ve3h9L3t5fS5wbmciLCJ0bXMiOmZhbHNlLCJzY2FsZURlcGVuZGVudCI6ZmFsc2UsIm1heFpvb20iOiIxOCIsImlzT3ZlcmxheSI6dHJ1ZX0=&j=66.14108/62.47375/66.68778/63.69324)
2. Save JNX for Zoom 15.

### Actual behaviour
nakarte.tk says:
> Failed to create JNX: network error

### Expected behaviour
JNX creation is OK with [old.nakarte.tk mapview](http://old.nakarte.tk/#m=9/66.36174/63.25378&j=66.14108/62.47375/66.68778/63.69324&l=E/N/J/F/K/W/Wp/-cseyJuYW1lIjoiT3BlblJhaWx3YXlNYXAiLCJ1cmwiOiJodHRwOi8ve3N9LnRpbGVzLm9wZW5yYWlsd2F5bWFwLm9yZy9zdGFuZGFyZC97en0ve3h9L3t5fS5wbmciLCJ0bXMiOmZhbHNlLCJzY2FsZURlcGVuZGVudCI6ZmFsc2UsIm1heFpvb20iOiIxOCIsImlzT3ZlcmxheSI6dHJ1ZX0).

### Configuration
OS: Linux
Browser: Firefox, Chrome

**Comment by wladich** [comment]
1. Сервер openrailwaymap.org жестко тротлит запросы тайлов. Множество запросов отрабатывают ровно 10 секунд по логам прокси. Плюс регулярно отвечает 503.
2. Похоже сервере ещё и просто тормозит, т.к. повторные скачивания jnx проходят получше, т.е. видимо срабатывает серверный кеш.
3. В старой версии таймаут на запрос тайлов был 20 секунд, сейчас 10. Сделал тоже 20 (для pdf и jnx), пусть будет.
