### ISSUE TITLE
Добавить возможность видеть статус активности добавления точки и сегмента трека

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#406]
Сейчас если кликнуть на "расстояние" и не убирать курсор, то появляется черная рамка и видно состояние "активности пункта" (ака "нажатие"). Хотелось бы, чтобы точка и сегмент работали также, а то пока курсор не уведешь с точки, неочевидно, активна эта функция или нет.

**Comment by wladich** [comment]
Про точку - рамку можно добавить, то что фон при наведении мыши становится светлым - это похоже баг.

С сегментом несколько менее понятно - нет режима "добавления сегмента", есть редактирование и рисование. Т.е. в моём понимании кнопка "+ линия" не включает режим добавления сегмента, а однократно добавляет сегмент и включает режим рисования. Соотв. делать кнопку включенной при каждом начале рисовании трека (например после клика на концевой ноде) неправильно. 

Теоретически можно объявить рисование сразу после нажатия этой кнопки "добавлением" и только в этом случае "включать" кнопку и при прекрашении рисования выключать.

**Comment by myadzel** [comment]
>Теоретически можно объявить рисование сразу после нажатия этой кнопки "добавлением" и только в этом случае "включать" кнопку и при прекрашении рисования выключать.

Да, чтобы было видно состояние. И чтобы по клику на кнопке (не уводя мыши) можно было "отключить" режим без начала рисования, аналогично с соседними кнопками.
