### ISSUE TITLE
при создании pdf имя файла по именам слоёв, формату бумаги, масштабу

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#43]
примерно как сделано для jnx

**Comment by wladich** [comment]
Предложение по составлению имени файла.

Имя файла должно получаться типа такого:
 * opentopo_500m_a4.pdf
 * topo_1000_passes_1000m_a3.pdf
 * osm_norway_summer_1333m.pdf

Имя файла состоит из 3 частей: 1) названия слоёв, 2) масштаб, 3) формат бумаги

### Названия  слоёв
Кейсы, какие слои включены у пользователя.
1. Один  базовый -- тривиально, имя только это слоя.
2. Базовый слой, сверху него оверлей типа topo, ggc, o-sport и т.п., т.е. интерес представляет именно оверлей. Базовый игнорируем, оставляем оверлей.
3. Базовый слой, сверху него несколько оверлеев. С большой вероятностью, включили всё подряд, напечатали, верхний оверлей. Берём только верхний слой. Вариант, что пользователь делал наложение ggc250 поверх topo500 идеально не обработаем, но так тоже неплохо.
4. кейсы 2 или 3, но для верхнего слоя в зоне печати нет ни одного тайла (опять включили всё подряд, напечатали, что видим).  Надо учитывать только оверлеи, для которых был скачан хоть один тайл.
4. Кейсы 1-4, плюс сверху один или несколько оверлеев типа перевалов вестры или норвежских троп, т.е. прозрачных -- добавляем имена всех таких оверлеев, но только тех, для которых скачался хотя бы один тайл.

Итого, для имён надо:
1. для всех слоёв с print: true добавить новую опцию shortName
2. Для всех слоёв с isOverlay: true добавить новую опцию isOverlayTransparent
3. Добавить проверку наличия и уникальности shortName и наличия isOverlayTransparent для оверлеев с print: true в layers.js (где order и code проверяются).
4. написать алгоритм составления списка имён слоёв с соответствии с кейсами.

### масштаб
из контрола печати, сколько метров в 1 см

### формат бумаги
если формат соответствует одному из стандартных a1-a5, то добавляем. Так сделано в контроле печати -- там при установке стандартного размера подчеркивание становится сплошным. 
Если не соответствует стандартному, то не добавляем размер совсем.

**Comment by myadzel** [comment]
У каждого слоя есть буквенный код, почему бы не использовать его в названии файла (первым идет всегда базовый)? Сплит кодов слоев - по заглавной букве (OZOt -> O/Z/Ot), для простоты без какого-либо разделителя. Формат бумаги всегда в мм (универсальный шаблон), если есть имя, то добавляется в скобках.

Например, `OZOt-10-210x297(A4).pdf`. Этот формат будет работать и для JNX/JPG, можно расширять формат, если это потребуется (координаты центра карты и т. д.).

**Comment by wladich** [comment]
Потомучто имя файла делается для людей, чтобы при печати нескольких файлов было проще понять, где что, какой уже напечатан, а какой ещё нет.

А "OZOt-10-210x297(A4).pdf" человеку (мне, например) гораздо менее понятно, чем slazav_traces_500m_a4.

А зачем координаты центра я не очень представляю. Было бы прикольно регион определять, но это слишком затратно.

**Comment by myadzel** [comment]
Теперь задача стала более понятна.

Однако, стоит добавить к имени файла хэш-сумму, хотя бы для того, чтобы не было дубликатов имен для, фактически, разных файлов.
