### ISSUE TITLE
Встроить геокодер

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#434]
Бывает очень удобно, чтобы найти нужную точку в пределах карты.

https://nominatim.org/release-docs/develop/api/Search/

Пример вызова API,
https://nominatim.openstreetmap.org/search?q=%D0%BE%D0%B7%D0%B5%D1%80%D0%BE%20%D0%BE%D0%BB%D0%B5%D0%BD%D1%8C%D0%B5&viewbox=38.32443237304688,55.372868141151756,40.886993408203125,55.89995614406812&bounded=1&format=json

**Comment by wladich** [comment]
Я как раз на днях в очередной раз смотрел, что есть доступного в плане поиска.

Nominatim как был, так и остался печален:
1. Плохие результаты по адресному поиску (примеры не сохранил)
2. Нет автодополнения.
3. Ограничение на 1 запрос в секунду на всех пользователей. Есть подозрение, что в отдельные моменты можем превышать.

Пока наиболее перспективным выглядит komoot, но у них что-то непонятное с временем ответа для "чужих" пользователей - у меня получается разброс от 100 мс до 10 с. То ли это агресивный throttling, то ли проблема с нагрузкой.

**Comment by myadzel** [comment]
Можно сделать универсально в интерфейсе, а подключать разных провайдеров.

**Comment by wladich** [comment]
Про свой instance photon - сколько нужно памяти ещё не смотрел, но база в распакованном виде сейчас занимает 135 Гб. Базу они дают скачать, но только целоком, diff-ов нет, соотв. это ещё 135Гб для обновления без заметного даунтайма. Размер базы будет расти вместе с размером дампа OSM.

**Comment by myadzel** [comment]
Оверхэд. Для простых вещей имхо не стоит так заморачиваться.

**Comment by wladich** [comment]
> Оверхэд. Для простых вещей имхо не стоит так заморачиваться.
В смысле оверкилл? 
Ну 135 я бы ещё подумал, учитывая, что бесплатных совсем хороших вариантов нет, а платные все что-то совсем дорогие, никаких донатов не хватит. 

Насчет "универсально и переключаться" - а собственно особо не на что. Есть nominatim с указанными недостатками и возможностью получить бан за превышение кол-ва запросов и photon с очень лаконичными условиями использивания, типа "пользуйтесь, но аккуратно и вообще ничего не обещаем".

**Comment by wladich** [comment]
Да, про количество пользователей - вот вчера уже было 4700 уникальных клиентов (по девайсам).

Т.е. что я хочу сказать: добавить готовый плагин для поиска - вообще не проблема. Но не хочется оказаться в ситуации, что приходится убирать фичу или аврально искать нового провайдера.

**Comment by wladich** [comment]
Вот, кстати, список сервисов: https://wiki.openstreetmap.org/wiki/Search_engines

**Comment by wladich** [comment]
Есть же ещё геокодер у mapy.cz - весьма неплохой поиск и бесплатный! Надо брать.
