### ISSUE TITLE
В Хроме после обновления уменьшились шрифты, многие элементы сместились на несколько пикселей, карты стали "в клеточку"

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#465]
Шрифты стали мыльные, не уверен, что это лечится

Размер кнопки печати стал 35.984, кнопка уехала на 1 пиксель влево.
Размер тайлов во вкладке Computed 255.992
Также изображение карты стало размытое, возможно из-за той-же причины

**Comment by wladich** [comment]
@myadzel @sikmir Посмотрите пожалуйста, в Винде и на Макоси такой же ужас в 84-ом Хроме? Я пока только на Федоре смотрел, ещё на Дебиане проверю.

**Comment by wladich** [comment]
Собсвенно, проблема не только в nakarte, а на всех сайтах.

**Comment by sikmir** [comment]
А можно скрин как это выглядит? В хроме 84 на макоси не замечаю ничего такого.

**Comment by wladich** [comment]
Chrome 83 прямо сейчас под рукой нет, сделал сравнение с Chromium. 

![chromium-nakarte](https://user-images.githubusercontent.com/1458202/87982768-92ece700-cad7-11ea-9627-966301e3df7c.png)
![chrome84-nakarte](https://user-images.githubusercontent.com/1458202/87982789-9a13f500-cad7-11ea-9c6e-74e952a1eb77.png)

**Comment by wladich** [comment]
Выяснилось, что помогает запускать Хром так: `google-chrome --force-device-scale-factor=1`

**Comment by myadzel** [comment]
В 84-м Хроме под MacOS все хорошо, да. Видимо проблема только в сборке под Linux.

А если убрать метатег viewport, что-то изменится при стандартном запуске?

**Comment by wladich** [comment]
Нет, без viewport так же криво.
Надо  бы в винде проверить, если там нормально, то можно расслабиться.

**Comment by wladich** [comment]
Считаем, что проблема в кривой сборке для Линуксов
