### ISSUE TITLE
Случайное удаление крайних точек при завершении рисования

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#469]
Ситуация: в процессе рисования сегмента трека, для завершения рисования на точке необходимо кликнуть дважды. Если между кликами практически не будет паузы, то сработает удаление, а не "фиксирование" конечной точки, которая в этот момент визуально в процессе редактирования.

**Comment by wladich** [comment]
Поправлю: для завершения рисования сегмента надо кликнуть один раз по концевой точке (и это сейчас работает). Проблемы:
1) если кликать быстро (первый клик - по ставили точку, второй - завершили рисование), это обрабатывается как двойной клик, т.е. точка удаляется. Этого по идее быть не должно, т.к. первый клик попадает на карту, а второй на маркер. Но почему-то на маркере ловится именно двойной клик.
2) Двойной клик на карте получается в текущей реализации no-op. Желательно при двойном клике на карте делать полезное действие, а именно добавить точку и завершить рисование.

**Comment by wladich** [comment]
Идеи про исправление:
1. Двойной клик, собственно, и не должен срабатывать на свежепоставленной точке. Надо посмотреть, чья это проблема - браузера, leaflet или nakarte. Если в nakarte - исправить, если в leaflet - посмотреть, исправлено ли в новых версиях и попробовать тоже поправить. В этом случае всё должно начать работать как надо, т.к. dblckick перестанет приходить на marker, а будет только обычный click.
2. Если п.1 не лечится, то да, придётся делать костыль.

**Comment by wladich** [comment]
Варианты костылей:
1. Считать клики
2. Запоминать время создания
3. Навешивать/снимать обфработчики событий.

**Comment by myadzel** [comment]
Добавил завершение рисования при двойном клике.

**Comment by myadzel** [comment]
> Идеи про исправление:
> 
> 1. Двойной клик, собственно, и не должен срабатывать на свежепоставленной точке. Надо посмотреть, чья это проблема - браузера, leaflet или nakarte. Если в nakarte - исправить, если в leaflet - посмотреть, исправлено ли в новых версиях и попробовать тоже поправить. В этом случае всё должно начать работать как надо, т.к. dblckick перестанет приходить на marker, а будет только обычный click.
> 2. Если п.1 не лечится, то да, придётся делать костыль.

А фишка в том, что если установлены click и dblclick на одном узле, то click раньше всегда отрабатывает. После "свежепоставленной" точки всегда будет dblclick. Делать таймеры в этом случае -- тоже костыль.

Уважаемый ресурс quirksmode не рекомендует делать два события (click/dblclick) на одном узле (https://www.quirksmode.org/dom/events/click.html), хотя делать эмуляцию dblclick (через таймауты) в этой ситуации мне видится довольно спорным решением.

**Comment by myadzel** [comment]
Так что можно считать, что pull решает эту проблему "by design")

**Comment by wladich** [comment]
> А фишка в том, что если установлены click и dblclick на одном узле, то click раньше всегда отрабатывает. После "свежепоставленной" точки всегда будет dblclick. Делать таймеры в этом случае -- тоже костыль.

Я же говорю, в моём представлении dblckick не должен срабатывать на маркере: "Этого по идее быть не должно, т.к. первый клик попадает на карту, а второй на маркер". Но я тут поигрался, похоже это поведение браузера.

**Comment by myadzel** [comment]
Замечу, что делать кастомную реализацию dblclick в обработчике click не очень хорошо, так же, как и эмуляцию скролла. Пользователь может выставить настройки и привыкнуть к ним, а кастомная реализация будет тупо бесить.

**Comment by wladich** [comment]
Так я вроде пока и не предлагал делать кастомную реализацию...

**Comment by myadzel** [comment]
Поменял логику: dblclick устанавливаем на точке, если количество кликов на ней равно 2, а для завершения рисования трека вынес проверку остановку рисования.

**Comment by wladich** [comment]
Пока не смотрел, но есть ещё одна непоследовательность: если при рисовании сделать двойной клик по противоположной концевой точке, то та точка удаляется и рисование останавливается. В идеале, я думаю, должно быть так: при рисовании двойной клик по любой существующей точке удаляет её (в том числе по любой существующей концевой), при двойном клике на карте (который в итоге приходит на созданную точку) - создание точки и остановка рисования.

**Comment by wladich** [comment]
Так, я тут подумал более внимательно - текущее состояние не такое и плохое: оно даёт возможность останавливать рисование без постановки точки а) без клавиатуры б) без прицеливания на последнюю точку. При этом комбо "поставить точку и завершить рисование" в общем то работает, просто требует небольшой паузы.

**Comment by wladich** [comment]
Я считаю текущее поведение правильным. 
Завершение рисования без постановки точки по двойному клику - это фича.
