### ISSUE TITLE
При копировании ссылки на трек убирать запрос и результат поиска

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#516]
Вынесено из https://github.com/wladich/nakarte/pull/468#issuecomment-669852288

**Comment by myadzel** [comment]
Правильно ли я понимаю, что здесь речь только про сам запрос?

(Что значит убрать результат поиска, я не понял.)

**Comment by myadzel** [comment]
https://github.com/wladich/nakarte/pull/1101

**Comment by wladich** [comment]
Fixed in #1105
