### ISSUE TITLE
смешение цветов наложенных треков

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#523]
Не баг, но забавное наблюдение. Загружаем дважды одинаковый трек. Одну версию делаем голубой, вторую красной. Выключаем-включаем голубой трек, результат наложения треков - темно-голубой. Выключаем-включаем красный трек - результат - серый, при том, что состояние интерфейса - то же. Получается, что отрисовка треков происходит не в том порядке, в котором они расположены в списке, а в зависимости от того, какой трек последним трогали.

**Comment by wladich** [comment]
Единственное место, где действительно заметен порядок треков - это наложение точек. И там оно внезапно работает правильно.

**Comment by wladich** [comment]
Предлагаю закрыть, т.к.:
* точки накладываются верно
* неправильный  порядок линий заметить сложно и неудобств не доставляет
* чтобы починить надо при каждом включении удалять все слои и добавлять заново, т.к. в leaflet нет механизма управления последовательностью векторных слоёв.

**Comment by slazav** [comment]
Да, закрыть, конечно. Я просто хотел поделиться странным найденным эффектом.
