### ISSUE TITLE
Отображение высоты под курсором

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#574]
Пришло на почту:
> Будет весьма полезно если по аналогии с координатами в этом меню будет так же отображаться высота.
Это позволит быстро ориентироваться в перепадах рельефа местности, например для поиска удобного места ночевки, доступности воды и т.п.
Возможно даже будет лучше не в этом меню, чтобы его не открывать постоянно, поскольку высота бывает нужна чаще чем координаты, а где-то внизу экрана.
Когда-то в gpsies была такая фича – очень помогала.

У меня такой потребности вроде не было, но возможно будет  полезно.

Идеи:
 - попробовать запрашивать имеющийся сервер высот при замирании мыши (и сбрасывать показания при начале движения мыши)
 - если будет совсем не комфортно (из-за задержки или из-за необходимости останавливать курсор) - думать про загрузку высот тайлами, но это, конечно сильно больше работы.
 - Хорошо бы как-то избежать добавления ещё одной кнопки снизу имеющихся.

**Comment by wladich** [comment]
Возможно исходная задача решится добавлением слоя с горизонталями из #403

**Comment by wladich** [comment]
Наблюдения:
* DEM размером 1920x1080 со сжатием DEFLATE имеет размер около 1 Мб
* ответы от сервера высот у меня дома приходят в среднем примерно за 20 мс

**Comment by wladich** [comment]
Статистика времени запроса высоты у пользователей.
Запрос из 1 точки. Статистика собиралась для случайных пользователей в случайное время, сериями по 1 минуте, минимальное количество запросов в серии 50.
Всего серий 2947

Колонки - оценка времени запроса в серии. Столбцы - оценка оценки серий.

  | mean | p50 | p80 | p95 | p99
-- | -- | -- | -- | -- | --
p50 | 71 | 60 | 70 | 99 | 165
p80 | 86 | 73 | 86 | 129 | 221
p90 | 92 | 78 | 92 | 141 | 247
p95 | 95 | 80 | 96 | 148 | 261
p99 | 98 | 82 | 99 | 156 | 272

**Comment by sikmir** [comment]
Не хватает возможности как с "Copy coordinates to clipboard" скопировать высоту выбранной точки. Постоянно под курсором запрашивать высоту возможно нет смысла, на то есть горизонтали. Сейчас реально приходится сначала скопировать координаты, потом дернуть `curl https://elevation.nakarte.me --data-binary 'xxx yyy'`.
