### ISSUE TITLE
убирать параметр fbclid из URL

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#579]
При переходе по ссылке из facebook в url добавляется длинный параметр fbclid=...
Пример: https://nakarte.me/?fbclid=IwAR3_fzOieX8SeVhDhY6l2xcaLDmBYWp2bZ9DFtzT2a5aW1ZLMoStUOzooDg#m=14/54.03374/-2.69049&l=O/Gbt
Не стоит ли его (да и вообще все лишние параметры) отрезать при загрузке?

**Comment by wladich** [comment]
Да, надо в конфиге nginx добавить редирект.

**Comment by wladich** [comment]
Убрал, работает и вроде ничего не сломалось.
