### ISSUE TITLE
Изменение системы рендера для slazav_maps

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#598]
Я сейчас перехожу на новую систему рендера карт (mapsoft -> mapsoft2). Пока перевел хребтовки, Подмосковье переведу, если не будет обнаружено проблем. Также, собираюсь публиковать гуглоплитки на сайте slazav.xyz/tiles/hr, в каком виде - можно обсуждать, текущий результат можно посмотреть тут:
https://nakarte.me/#m=3/63.31268/81.03516&l=O/Q/-cseyJuYW1lIjoic2xhemF2IG1vdW50YWluczEiLCJ1cmwiOiJodHRwOi8vc2xhemF2Lnh5ei90aWxlcy9oci97eH0te3l9LXt6fS5wbmciLCJ0bXMiOmZhbHNlLCJzY2FsZURlcGVuZGVudCI6dHJ1ZSwibWF4Wm9vbSI6MTMsImlzT3ZlcmxheSI6dHJ1ZSwiaXNUb3AiOnRydWV9

В репозитории https://github.com/slazav/map_hr теперь содержится описание системы знаков и Makefile, который делает все необходимое, в том числе и плитки (кажется, система получилась гораздо проще, чем раньше). Используется в основном mapsoft2, старый mapsoft пока используется только для получения индексных картинок на отдельные районы, постепенно его изведу.

Никаких изменений собственно в картах пока нет, с действиями можно не торопиться, но рано или поздно надо бы переключиться. Можно генерить плитки так же, как это сделано у меня в makefile'е, или зеркалировать их с slazav.xyz
Дело осложняется тем, что интерфейс mapsoft2 еще не очень стабилен, я хочу играться с картами и смотреть, что там было бы удобно поменять... Ну и вообще думаю, не порезать ли все на номенклатурные километровки, не разделить ли разные горные районы по отдельным репозитариям... Постараюсь держать в курсе.

**Comment by wladich** [comment]
Мне, разумеется, лучше всего ничего не делать :)

> рано или поздно надо бы переключиться

Почему? Ты планируешь добавить изменения в карты, несовместимые со старой системой рендеринга? Или новая система будет делать другую картинку, не такую как старая?

**Comment by slazav** [comment]
Когда-нибудь планирую, но не сейчас. Я буду держать в курсе.
Я пока плохо понимаю, как все будет развиваться, на самом деле. Так что, наверное, лучше пока ничего и не делать.

**Comment by wladich** [comment]
Хорошо.
