### ISSUE TITLE
server side components

### ISSUE THREAD

**Issue by javierpose** [wladich/nakarte#600]
Hi

I would like to know what components I have to install on my server to use these services without calling your server:
    CORSProxyUrl: 'https://proxy.nakarte.me/',
    elevationsServer: 'https://elevation.nakarte.me/',
    wikimediaCommonsCoverageUrl: 'https://tiles.nakarte.me/wikimedia_commons_images/{z}/{x}/{y}',
    tracksStorageServer: 'https://tracks.nakarte.me',

**Comment by sikmir** [comment]
CORSProxyUrl: any CORS proxy, for example nginx
elevationsServer: [elevation_server](https://github.com/wladich/elevation_server) or [ElevationServer](https://github.com/wladich/ElevationServer)
wikimediaCommonsCoverageUrl: [mbtileserver](https://github.com/consbio/mbtileserver) + [wikimedia_commons_images.mbtiles](https://tiles.nakarte.me/files/wikimedia_commons_images.mbtiles)
tracksStorageServer: [tracks_storage_server](https://github.com/wladich/tracks_storage_server)

**Comment by wladich** [comment]
elevationsServer - I suggest to use new Golang version https://github.com/wladich/elevation_server. The server exposes http interface, so you need to simply make a proxy_pass config for nginx.
You can build data from hgt files downloaded from viewfinderpanoramas.com or I can provide the prepared file. You need to get it only once as DEM data is not updated.

wikimediaCommonsCoverageUrl - as @sikmir wrote, you can serve it with any mbtiles server. I use my own: https://github.com/wladich/mbserver, but I believe there are better ones. The data is updated twice a month, you can download it from my server or build it yourself: https://github.com/wladich/wikimedia_photos_for_nakarte. If you chose the latter, ping me and I will add links for DB download and few maintenance scripts to that repo.

tracks server - https://github.com/wladich/tracks_storage_server. You need postgresql installed. The server has wsgi interface, I run it with uwsi and nginx.

cors server: here is a basic config for nginx:
```
server {
  listen 80;
  listen 443 ssl;

  server_name proxy.nakarte.tk proxy.nakarte.me;

  more_clear_headers Access-Control-Allow-Origin;
  more_clear_headers Access-Control-Allow-Credentials;
  more_clear_headers Access-Control-Expose-Headers;
  more_set_headers 'Access-Control-Allow-Origin: $http_origin';
  more_set_headers 'Access-Control-Allow-Credentials: true';
  more_set_headers 'Vary: Origin';
  more_set_headers 'Access-Control-Expose-Headers: Content-Disposition';

  location / {
    return 404;
  }

  location ~ ^/(https?)/([^/]+)(/.*)$ {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Sec-Fetch-Site "";
    proxy_connect_timeout 30;
    proxy_read_timeout 30;
    default_type text/plain;

    set $original_url $1://$2$3$is_args$args;
    set $original_host $2;
    set $original_scheme $1;
    proxy_pass $original_url;
    proxy_ssl_server_name on;
    proxy_redirect ~^(https?)://(.+) $scheme://$host/$1/$2;
    proxy_redirect ~^/([^/].+) $scheme://$host/$original_scheme/$original_host/$1;

    proxy_ignore_headers Set-Cookie Expires Cache-Control Vary X-Accel-Expires;

    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;

  }
}
```
Add logging and cache to your taste. Another thing it is doing is adding cookies for Strava layers (strava will not work without them) but I am not sure I want to share this part.

**Comment by sikmir** [comment]
> elevationsServer - I suggest to use new Golang version https://github.com/wladich/elevation_server.

Could you please add README with few lines about how to build elevation_server, I've tried some sort of 'go build -o elevation_server cmd/elevation_server/main.go` with no success.

**Comment by wladich** [comment]
@sikmir 
Please have a look at https://github.com/wladich/elevation_server/pull/1
BTW: you can download prebuilt binaries from Releases section: https://github.com/wladich/elevation_server/releases

**Comment by javierpose** [comment]
Hi @wladich 
I was especially interested in managing cookies with strava, but I understand you want to keep that for yourself. I think your project is the best and the most complete one made with Leaflet and I only miss a routing module to create automatic routes, like tmuguet/map2gpx. Thanks a lot for share.

**Comment by yalamber** [comment]
Hello @wladich, 
Can you give us some pointer on how you approached with strava cookie settings, when trying to run tests it's failing as Too Many Requests for strava urls, It seems like strava blocked my server's ip

**Comment by wladich** [comment]
Loading tracks from Strava requires providing session cookie for authenticated user. 
It is also beneficial to configure cache on proxy server to reduce number of requests to remote servers.
