### ISSUE TITLE
Национальные карты надо обрезать по границам страны

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#603]
Например, так: https://github.com/aparshin/leaflet-boundary-canvas

**Comment by sikmir** [comment]
Да, очень актуально, например слой Finland Topo удобней было бы сделать как overlay и обрезать по границе.

**Comment by wladich** [comment]
Конкретно про Finland Topo - можно (нужно) сделать overlay + обрезку по прямоугольнику.  А вот контур, кажется, не получится, по той же причине, почему для него не работает PDF и JNX: их сервер не ставит CORS  заголовки и банит мой сервер, соответственно img, полученные по ответам без CORS-заголовков нельзя использовать для рисования на canvas

**Comment by wladich** [comment]
Теперь фины забанили и мой домашний IP. 
@sikmir У тебя такого не случается?

**Comment by sikmir** [comment]
> Теперь фины забанили и мой домашний IP.
> @sikmir У тебя такого не случается?

Нет вроде, https://retkikartta.fi/ работает у меня.

**Comment by wladich** [comment]
Да, у меня уже снова заработало. Возможно их система зашиты так реагирует на использование карты в QGIS

**Comment by wladich** [comment]
В итоге Finland topo перенесена в оверлеи, обрезка сделана с точностью до тайла. 
Чтобы сделать обрезку по контуру (а заодно и печать и JNX), надо хостить свою версию.
