### ISSUE TITLE
убрать загрузку треков gpslib (31.02.2021)

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#658]
gpslib.net и gpslib.ru не отвечают несколько дней.
Если до конца февраля не восстановится, убрать загрузку треков и тесты

**Comment by sikmir** [comment]
@wladich Михаил Кривый (автор gpslib.ru) ушел из жизни 21 апреля 2019 после тяжелой болезни, ему было 38 лет. Сайт gpslib.ru как-то еще на автомате продолжал работать, с невалидным сертификатом правда, но сейчас видимо все, хостинг истек, уже некому восстановить..

**Comment by wladich** [comment]
Видимо кто-то присматривает за сайтом, он снова работает.

**Comment by sikmir** [comment]
Сертификат по прежнему протухший:
> The certificate for www.gpslib.ru expired on 7/26/2019.

В ноябре будет понятно, присматривает ли кто-то за доменом:
```
$ whois gpslib.ru | grep free
free-date:     2021-11-30
```
