### ISSUE TITLE
В интерфейс редактирования кастомного слоя добавить цвет подложки

### ISSUE THREAD

**Issue by slazav** [wladich/nakarte#665]
У меня возникло такое пожелание. При добавлении кастомного слоя (base layer), хочется иметь возможность настроить цвет подлжки и, соответственно, не хранить пустые плитки, или использовать плитки с прозрачностью. Сейчас там серый цвет. Насколько это реализуемо, осмысленно и т.п.?

**Comment by wladich** [comment]
Раз есть пустые плитки, видимо слой не глобальный. Почему его тогда не добавить как оверлей?

**Comment by slazav** [comment]
Слой глобальный, но, например, хочется сделать все океаны однотонными, но не хранить много однотонных плиток. 
Что-то в таком духе (временная ссылка):  https://nakarte.me/#m=5/43.50075/-15.44678&l=-cseyJuYW1lIjoiYWxvc19zbG9wZXMiLCJ1cmwiOiJodHRvOi8vc2xhemF2Lnh5ei90aWxlcy9kZW1fcy97en0ve3h9LXt5fS5wbmciLCJ0bXMiOmZhbHNlLCJzY2FsZURlcGVuZGVudCI6ZmFsc2UsIm1heFpvb20iOjksImlzT3ZlcmxheSI6ZmFsc2UsImlzVG9wIjp0cnVlfQ==
Хотя, наверное, это можно и на уровне сервера решить.

**Comment by wladich** [comment]
Да, по-моему такие вещи надо на стороне сервера определять.
Если ты хранишь плитки файлами, то можешь использовать директиву nginx try_files для замены отсутствующих плиток.
