### ISSUE TITLE
Не сбрасывать данные при переходе по ссылке

### ISSUE THREAD

**Issue by knyazevdev** [wladich/nakarte#689]
Добрый день!

На данный момент при переходе по ссылке, созданной другим пользователем (Copy link for all tracks, например), сбрасываются все свои отрисованные треки.

Еще хуже, когда заходишь на сайт какого-то мероприятия, а там установлен iframe с треком, и все собственные треки пропадают.

Нельзя сделать так, чтобы при переходе по ссылке треки и данные добавлялись к старым?

**Comment by knyazevdev** [comment]
Ок, будем ждать, а то там с 2018 года открыто )

**Comment by tarwirdur** [comment]
Может открытым тикет оставить?

**Comment by wladich** [comment]
Насколько я понял, вопрос возник из-за неясности, что означает закрытие и открытие вкладки с сайтом.
Вариант 1: Закрыли (штатно) вкладку - всё, сессия закончилась. Можно её восстановить по "Ctrl-Shift-T". При аварийном закрытии браузера вкладка-сессия тоже восстанавливается.
Вариант 2: Закрыли вкладку - сессия сохранилась. Открыли новую вкладку - достали последнюю сохранённую сессию.

Сейчас реализован вариант 2, но плохо (#228).
Проблема автора issue должна решаться открытием ещё одной вкладки.

**Comment by tarwirdur** [comment]
Сейчас кажется так:

* открываем вкладку рисуем какой-нибудь трек (1), закрываем вкладку.
* переходим по ссылке с другим треком (2), закрываем вкладку.
* открываем новую вкладку - **видим первый трек (1)**, закрываем.
* открываем опять ссылку с треком (2), добавляем новый трек (например, просто измеряем состояние между каким-то точками на карте), закрываем вкладку.
* открываем новую вкладку - **видим второй трек (2)**

Такое поведение мне кажется не всегда удобным и очевидным.

**Comment by tarwirdur** [comment]
> Проблема автора issue должна решаться открытием ещё одной вкладки

А вот это - какое-то совсем неочевидное поведение.

**Comment by knyazevdev** [comment]
Всё гораздо проще. Вот алгоритм получения проблемы:

1. Открываем nakarte.me. Рисуем любой трек.
2. Уходим по своим делаем, вкладку закрываем
3. От друзей получаем ссылку, например https://nakarte.me/#m=10/55.60318/38.00789&l=O&nktl=KYOMJFo4WrootHEbXrMSTA
4. Переходим по этой ссылке. Всё, все свои отрисованные треки утеряны

**Comment by myadzel** [comment]
Как вариант простого решения: 

1) каждый локал-стораж имеет свой идентификатор, сохраненный в нем (условный sid)

2) каждая ссылка "поделиться" имеет не только атрибут nktl, но и sid

3) сохраняя данные в локал-стораже при чтении с сервера хранения, мы получаем sid и сохраняем с треком

4) при открытия трека по ссылке сохраняет sid в адресной строке

5) при открытии nakarte.me без sid - читаем sid текущего стоража (сохраненное в нем единожды) и получаем список "своих" треков по этому sid

**Comment by wladich** [comment]
> Всё гораздо проще. Вот алгоритм получения проблемы:
> 
> 1. Открываем nakarte.me. Рисуем любой трек.
> 2. Уходим по своим делаем, вкладку закрываем
> 3. От друзей получаем ссылку, например https://nakarte.me/#m=10/55.60318/38.00789&l=O&nktl=KYOMJFo4WrootHEbXrMSTA
> 4. Переходим по этой ссылке. Всё, все свои отрисованные треки утеряны
> 
> И вот хотелось при переходе по ссылке объединения треков

Вот я и говорю, что эта конкретная проблема решается открытием ещё одной вкладки с nakarte, в ней откроется трек из п.1. 
Логика здесь такая: треки из каждой закрытой вкладки помещаются в стек. При открытии вкладки без треков ссылке, трек достаётся из стека.  Недостатки идеи и ошибки реализации обсуждаются в #228.

**Comment by wladich** [comment]
> Как вариант простого решения:

Я пока ничего  не понял. Какая именно проблема решается? Их в этом таске уже две или три.

**Comment by wladich** [comment]
Решение по issue: исходная проблема - проблема документации, ответ на неё в https://github.com/wladich/nakarte/issues/689#issuecomment-830028810

Проблема нестабильности, особенно при заакрытии/открытии браузера с несколькими вкладками зафиксирована в #228.

Закрываю тред.

**Comment by wladich** [comment]
Забыл добавить: так же сюда относится #117 

Автоматическое объединение делать не надо, это будет совсем странно и неожиданно.

**Comment by knyazevdev** [comment]
Я всё-таки снова открою этот вопрос.

Вот алгоритм потери всех своих треков. Открываем nakarte.me, рисуем свои треки. Закрываем вкладку.

Гуляем по сайтам, видим ссылку и переходим по ней:

![image](https://user-images.githubusercontent.com/37297237/127849291-9ac754d1-a044-4ef4-ac67-52000f06300b.png)

Сама ссылка: [link](https://nakarte.me/#m=5/56.03523/63.06152&l=T&nktl=PukhyRo2q3n0mvwgFvT3cg)

Всё, все свои треки потеряны. Как видите, в таком случае даже нельзя понять, что переходишь на nakarte.me и всё теряешь.

**Comment by tarwirdur** [comment]
> Всё, все свои треки потеряны.

Нет, они не потеряны. Вы можете открыть ещё одну вкладку с nakarte (не закрывая уже открытую!) и тогда в ней откроется предыдущая сессия (с нужными вам треками). Ещё одна вкладка - та сессия, которая была ещё раньше.

@wladich но такое поведение пользователям вряд ли понятно.

**Comment by knyazevdev** [comment]
Я же не специально пытаюсь баг найти, а на практике сталкиваюсь регулярно с этим) Интервал между открытиями вкладок может измеряться и днями - конечно за это время я могу закрыть "чужую открытую", даже не подумав об этом.

Сейчас мне приходится периодически делать "бэкап треков", через "Copy link for all tracks", и открывать все сторонние ссылки incognito, но всё равно иногда не уследишь)

Такая проблема встречается не только у меня.

**Comment by myadzel** [comment]
> Нет, они не потеряны. Вы можете открыть ещё одну вкладку с nakarte (не закрывая уже открытую!) и тогда в ней откроется предыдущая сессия (с нужными вам треками). Ещё одна вкладка - та сессия, которая была ещё раньше.

Увы, в мобильном Хроме все теряется.

**Comment by wladich** [comment]
Fixed in #1258
