### ISSUE TITLE
Поиск места или постановка точек по координатам

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#72]
Подумать о:
1. Что реально нужно -- показать место или поставить точку?
2. Куда запихнуть: контекстное меню точки, контрол координат или ещё куда
3. Интерфейс: поле ввода, варианты  "что вы хотели сказать", поменять местами шируоту и долготу.

**Comment by myadzel** [comment]
Дополню. 

4. Парсинг различного формата координат.

**Comment by AndreevYuri** [comment]
Дополню. 
5. Нужна функция поиска точки:
- по названию точки
- по кооординатам

**Comment by wladich** [comment]
Всё сделано в #468
