### ISSUE TITLE
Слой Sputnik.ru

### ISSUE THREAD

**Issue by silentbay** [wladich/nakarte#795]
Карта с сайта http://maps.sputnik.ru
Формат https://tilessputnik.ru/{z}/{x}/{y}.png

**Comment by wladich** [comment]
Какие у этой карты достоинства, каких нет у уже имеющихся карт?

Сходу заметил проблемы: 
* грунтовки исчезают на 15 уровне
* тропы есть только от 18 уровня
* за пределами России нормально показывает только до 15 уровня. Для более подробных отдaёт 502

**Comment by silentbay** [comment]
Как таковых достоинств, кроме чистого стиля карты, нет.

**Comment by wladich** [comment]
Тогда я считаю, что недостатки перевешивают преимущество.
Закрываю.
