### ISSUE TITLE
Проблемы с отображением кириллический названий треков через nktj

### ISSUE THREAD

**Issue by tarwirdur** [wladich/nakarte#796]
Пример: https://nakarte.me/#nktj=W3sibiI6ItCi0LDQudC80YvRgCAyMDIxIiwidSI6Imh0dHBzOi8vdGFyd2lyZHVyLmdpdGh1Yi5pby90cmFja3MvYjQxZDkwNmZhODAzYmY0N2FmZmMwNzNlOGQ3NTYxNjMuZ3B4In1dCg==

Параметр сформирован так:
```
echo "[{\"n\":\"Таймыр 2021\",\"u\":\"https://tarwirdur.github.io/tracks/b41d906fa803bf47affc073e8d756163.gpx\"}]" | base64 | tr -d '\n' | tr '+/' '-_'
```

Проблема в https://github.com/wladich/nakarte/blob/master/src/lib/leaflet.control.track-list/lib/parsers/urlSafeBase64.js

Решения: https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem

**Comment by wladich** [comment]
Проблема примерно там, но не совсем. `atob`, как и положено, получает байты на входе и возвращает байты на выходе.
В итоге для примера из описания получаем вполне нормальный JSON со строками в однобайтовой кодировке utf-8.

Кстати, это будет верно только при выполнении `echo ...` с  utf-8 локалью. При другой кодировке локали результат будет совсем другим. Поэтому крайне не рекомендуется генерировать json таким образом. Лучше использовать что-то вроде
```
import json
import base64
print(base64.b64encode(json.dumps([{"n": u"Таймыр"}]).encode('ascii'))) 
```

А вот JSON.parse() не считает нужным декодировать utf-8, несмотря на https://tools.ietf.org/id/draft-ietf-json-rfc4627bis-09.html (п. 8.1), что, в принципе, понятно, т.к. мы ему передаём не байты, а строки...

При подобном бардаке с кодировками в JS самый правильный выход это эскейпить всё, что не ascii -- см. питонячий пример выше.
Но можно и принять, что utf-8 это вроде как самая популярная кодировка и пытаться декодировать после `atob`.
