### ISSUE TITLE
Cannot close elevation widget

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#8]
### Steps to reproduce
1. New track / Add track segment
2. Show elevation profile
3. Action is failed for some reason (it depends on track):
 - Chrome says: "Failed to get elevation data: Cannot read property 'length' of undefined"
 - Firefox says: "Failed to get elevation data: l is undefined"
4. After the fail it's impossible to close elevation widget (see screenshots).
![screenshot-chrome](https://user-images.githubusercontent.com/688044/28744133-42db9dc4-7463-11e7-9766-c1611ef171e1.jpg)
![screenshot-firefox](https://user-images.githubusercontent.com/688044/28744134-42dbde7e-7463-11e7-9cc7-ae5b85fa72f0.jpg)

**Comment by wladich** [comment]
Не получается воспроизвести.
Нашёл примерно в том месте другую ошибку, исправил
Проверьте пожалуйста, может и эта исчезла.

**Comment by sikmir** [comment]
No, problem still exists.
You can reproduce it with [this track](https://www.gpslib.ru/tracks/download/73000.gpx). By the way, what's the cause of "Failed to get elevation data"? It happens quite often with my tracks.

**Comment by wladich** [comment]
Была недоработка в сервере высот (для точек с неизвестной высотой отдавал аномальное значние) и ошибка в контроле. Починил в обоих местах, заодно для мест без высотных данных делаем пропуск в линии профиля, раньше рисовали по уровню 0.

**Comment by sikmir** [comment]
Thanks, it works now.

**Comment by wladich** [comment]
Про "Failed to get elevation data:" -- должно быть продолжение сообщения. Сходу в логах проблем не смог найти.
