### ISSUE TITLE
Скачивание трека без высоты требует подключения к серверу высот

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#821]
Попытка скачать трек в горах из списка не увенчалась успехом: скачиваю трек без высот, но сайт запрашивает подключение.

![Screenshot_20210809-143901](https://user-images.githubusercontent.com/873432/128741028-91a8c037-a4fe-4bc6-814b-2a0238ebcce6.png)

**Comment by myadzel** [comment]
Благодарю.

**Comment by wladich** [comment]
Вчера забыл на прод выкатить. Сейчас выкатил.
