### ISSUE TITLE
Locus ставит треки с nakarte в конец списка

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#829]
Вынесено из комента https://github.com/wladich/nakarte/issues/573#issuecomment-887359615, автор @vsespb

----

При импортировании .gpx в locus 4, треку проставляется дата 01.01.1970 и он попадает в конец списка треков в папке, у остальных треков в папке нормальная дата - то когда его создали или когда его записали (проехали). А эти 1970 выбиваются из этой стройной системы.
Если посмотреть содержимое .gpx, то такая дата встречается только в отдельных точках, так что наверное это из-за неё.
```
			<trkpt lat="60.075276" lon="30.307503"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="60.075126" lon="30.306988"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="60.074947" lon="30.307111"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="60.074671" lon="30.306129"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="60.074821" lon="30.305684"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="60.074883" lon="30.305749"><time>1970-01-01T00:00:01.000Z</time></trkpt>
			<trkpt lat="60.075191" lon="30.305314"><time>1970-01-01T00:00:01.000Z</time></trkpt>


```

Из тикета https://github.com/wladich/nakarte/issues/90 не понял, почему используется "левое" время, почему бы не ставить настоящее - время создания трэка или время экспорта?

**Comment by wladich** [comment]
"Левое" время в точках это чтобы сразу было понятно, что оно не настоящее, чтобы не вводить людей в заблуждение, будто в треке есть нормальное время.
Но судя по схеме, время трека можно указать в gpx/metadata/time и возможно Locus сможет это прочитать.

**Comment by wladich** [comment]
@vsespb, Пожалуйста, проверьте, как Locus сортирует файл из архива во вложении: [test_date.zip](https://github.com/wladich/nakarte/files/7041467/test_date.zip)

**Comment by vsespb** [comment]
@wladich да, проблема исправилась, файл наверху списка, дата у него 23.08.2021

**Comment by wladich** [comment]
Выложил.
