### ISSUE TITLE
Failed to open UTF8 OziExplorer files with BOM

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#84]
It happened that I got some UTF8 OziExplorer file with [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) and nakarte failed to open it.
### Steps to reproduce
It can be easily reproduced with any file:
```bash
$ curl https://www.gpslib.ru/tracks/download/78392.plt | uconv -f utf-8 -t utf-8 --add-signature > test.plt
```
### Actual behaviour
Error: 

> File "test.plt" has unsupported format or is badly corrupt, no data could be loaded.

**Comment by wladich** [comment]
А сам Ozi такие файлы открывает? 
Я думал, у него во всех файлах кодировка типа "ANSI"

**Comment by sikmir** [comment]
Да, открывает.
