### ISSUE TITLE
Некорректное позиционирование списка карт при уменьшении масштаба страницы

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#845]
![Screen Shot 2021-09-09 at 11 13 53](https://user-images.githubusercontent.com/873432/132649038-4325ccb1-525c-44ac-8050-16d9762c1f53.png)

**Comment by wladich** [comment]
Хм, я был уверен, что `user-scalable=0` запрещает масштабировать страницу, но в Chrome это не так.
`float: left` тоже пригодится, но вообще надо почитать, как правильно запретить масштабирование

**Comment by myadzel** [comment]
Лучше не запрещать.

**Comment by wladich** [comment]
Ну вообще я это делал специально и оно какое-то время работало. 
Идея именно в том, чтобы такой фигни с версткой не было. Ещё была похожая проблема на айфонах с полями ввода - лечилось именно запретом масштабирования: https://github.com/wladich/nakarte/pull/468#issuecomment-665561934

**Comment by wladich** [comment]
Пока не закрываю, может подумаю как изменение масштаба всё-таки запретить. Оно плохо сочетается с зумом карты.
