### ISSUE TITLE
Wrong JNX files projection

### ISSUE THREAD

**Issue by tumic0** [wladich/nakarte#89]
The generated JNX maps have a Web Mercator projection instead of the Lat/Lon (2D geographic) projection specified in the "standard" (and used by Garmin). This leads, by definition, to some display distortions/inaccuracies, for example see the attached screenshot from GPXSee:
![jnx-mercator](https://user-images.githubusercontent.com/11480505/40958180-9c7d2f8a-6898-11e8-93f9-59c16539fc17.png)

If you are not able to correctly re-render the tiles, at least specifying the projection in the JNX file could help so 3rd party SW tools can render the maps correctly. My suggestion would be to add the EPSG code (3857 in case of WGS84/Web Mercator) to the "Unknown" level description field with offset 0x0C that you actually fill with a magic value of '2'.

**Comment by tumic0** [comment]
Maybe a better place for the projection info is the "Usually empty string. Does not seem to be currently used." string in the "Map info sub-block". A standard identifier string like used in WMS/WMTS - "EPSG:3857" - instead of the current empty string would be all that is needed to correctly display the JNX maps.

**Comment by wladich** [comment]
JNX format is intended to be used  primarily in Garmin devices. I haven't seen black stripes in my Garmin 78. Do you have an example of JNX files generated in nakarte.tk being incorrectly displayed  in some Garmin devices?

**Comment by tumic0** [comment]
I don't have any Garmin device, sorry. But all other JNX maps I have seen are in lat/lon (geographic 2D) projection like described at http://whiter.brinkster.net/en/JNX.shtml. The Garmin devices may draw the map differently so maybe the map looks OK and the tracks are distorted/displaced. However generally something will be wrong when the projection of the map is not the expected one.

**Comment by wladich** [comment]
Garmin stretches tiles linearly according to coordinates of corners. 
Tiles are relatively small and coordinates of tile corners are correct (I hope they are), so distortions should be neglible. By the way, Garmin displays map with projection which looks similiar to web mercator, so it is possible that jnx from nakarte finally are displayed with less distortions then other maps (but again those distortions should be hard to notice)

**Comment by tumic0** [comment]
Garmin may stretch the tiles as you say so there are no gaps, but the distortion is still there. I understand, that you don't want to reproject the tiles as it is quiet a lot of work and the error is not that visible on Garmin devices, but adding the projection code to the map info block can help 3rd party tools to display the maps correctly and it is just a one line patch - simply replacing "" (empty string) with "EPSG:3857" is all that is needed.
