### ISSUE TITLE
Совместимость GPX-файлов с Garmin Connect

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#90]
В соответствии со схемой http://www.topografix.com/GPX/1/1/gpx.xsd, элемент time не является обязательным, но популярный сервис Garmin Connect не принимает GPX-файлы, в которых нет этого элемента. 

Обыватели не могут понять причину и прогоняют проблемные файлы через gpsies, к примеру, нормализуя их.

Возможно, стоит сделать исключение и добавить <time> для элементов <trkpt> с текущим временем?

**Comment by wladich** [comment]
Расскажи, пожалуйста, для чего в Garmin Connect используются импортированные треки? Для планирования маршрутов или для отчетов о тренировках или ещё для чего.

**Comment by myadzel** [comment]
Для заливки в часы (навигация). Там по-другому никак не залить трек.

**Comment by wladich** [comment]
А, ну тогда можно добавить какое-нибудь определённо левое время, типа 1 января 1970 г., чтобы сразу было понятно, что время ненастоящее

**Comment by myadzel** [comment]
Ага:

```js
new Date(0).toISOString()
```
