### ISSUE TITLE
Возможно ли добавление новых слоев для специализированных районов?

### ISSUE THREAD

**Issue by axti** [wladich/nakarte#902]
Есть ли возможность комбинировать разные источники тайлов? Например добавить в выбор тайлы с этого ресурса: https://retkikartta.fi 
Есть ли какой-то readme для этого?

**Comment by sikmir** [comment]
"Add custom layer"?

**Comment by wladich** [comment]
Конкретно карты с retkikartta.fi уже есть - в настройках слоёв "Шестерёнка / Topo maps / Finland topo"
Добавлять TMS-подобные слои в свой браузер можно с помощью "Custom layers" - иконка с карандашом; в верхней части диалога там есть ссылка на документацию Leaflet по шаблонам, которые можно использовать в URL тайлов.

**Comment by axti** [comment]
@wladich классно, не знал и никогда в настройки не заглядывал.
