### ISSUE TITLE
Ещё два слоя overlay: официальные вело- и пешие маршруты Европы

### ISSUE THREAD

**Issue by pgavrilov** [wladich/nakarte#92]
Кроме cycling и hiking там ещё есть верховая езда, МТБ, ролики и горнолыжи, но они представлены в следовых количествах и такого интереса не представляют. Маршруты за пределами Европы тоже есть, но их настолько мало, что можно не принимать их во внимание.

Покрытие западной Европы официальными вело- и пешими маршрутами, судя по карте, очень плотное.

https://tile.waymarkedtrails.org/cycling/{z}/{x}/{y}.png
Официальный сайт (показывает описание треков, отображаемых в данный момент на экране) https://cycling.waymarkedtrails.org/

https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png
Официальный сайт (показывает описание треков, отображаемых в данный момент на экране)
https://hiking.waymarkedtrails.org/

Тип: Overlay
Max zoom: 18

![default](https://user-images.githubusercontent.com/3817702/41008144-1b0abcca-6932-11e8-9c9d-38fbf64cd104.jpg)

**Comment by wladich** [comment]
Быстро посмотрел, вроде интересно. 
Как я понял, интерес представляет именно в интерактивном виде, чтобы можно было посмотреть информацию о маршруте и скачать его в виде трека.

**Comment by pgavrilov** [comment]
Не только. В виде карты тоже имеет смысл - для планирования трека так,
чтобы его большая часть проходила с опорой на сеть этих велодорожек.

Насколько я успел увидеть, вся обозначенная на карте сеть - это либо
выделенные велодорожки, либо велополосы. В Германии гуглопанорамы забанены,
но в Австрии можно легко отсмотреть указанные улицы и посмотреть, как эта
сеть выглядит на местности.

чт, 7 июня 2018 г., 20:54 Sergej Orlov <notifications@github.com>:

**Comment by wladich** [comment]
Попробовал, смысл в картах есть, добавлю.

**Comment by wladich** [comment]
Сначала добавляем как есть.
Не забыть сделать таск на добавление интерактивных функций -- информация о маршруте и скачивание (сначала проверить адекватность на родном сайте)
