### ISSUE TITLE
Топооснова ЕЭКО

### ISSUE THREAD

**Issue by Xeenych** [wladich/nakarte#936]
Рсреестр в качестве подложки стал использовать топооснову ЕЭКО - это наследник карт ГГЦ.
Ссылки на тайлы там примерно такие:
https://pkk.rosreestr.ru/GISWebServiceSE/service.php?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=PKKm&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&TILEMATRIX=14&TILEROW=6034&TILECOL=10263&FORMAT=image%2Fpng

Можно доабвить их в качествет основных слоев?

**Comment by slazav** [comment]
О, можно найти те места, которых не было в ГГЦ. Спасибо за информацию!

**Comment by Xeenych** [comment]
Этот слой можно подключить как custom, но было бы полезно его видеть среди основных

**Comment by Xeenych** [comment]
В принципе, если почитать документацию на ГИС Панорама и их WebServoce, то может, получится вытянуть другие масштабы и тайлы большего размера

**Comment by wladich** [comment]
С моей стороны границы блокировка по IP:
```
$ nmap -p 80,443 pkk.rosreestr.ru -Pn
Starting Nmap 7.80 ( https://nmap.org ) at 2022-05-17 22:21 CEST
Nmap scan report for pkk.rosreestr.ru (217.77.104.195)
Host is up.
rDNS record for 217.77.104.195: 195-104-77-217.host.cirex.ru

PORT    STATE    SERVICE
80/tcp  filtered http
443/tcp filtered https
```
с другой стороны точно не знаю, но похоже на начало разложения:
![globalcheck net_en](https://user-images.githubusercontent.com/1458202/168903411-2c837941-988c-48d5-ab27-6b05cb4070a1.png)

**Comment by slazav** [comment]
Я скачал у них Подмосковье и что-то еще типа Буордаха (но в не слишком архивном виде, склеив плитки в листы).
Вообще, на мой взгляд карта по Подмосковью очень хорошая, лучше ГГЦ. Но мелкий рендер, конечно, сильно мешает.

**Comment by slazav** [comment]
Вроде, эта же карта доступна в хорошем разрешении и без блокировки заграницы вот тут: https://portal.fppd.cgkipd.ru/map?data=eekoers&data=eekomap&data=EekoGMap

**Comment by wladich** [comment]
Причём не просто по-другому, а ещё и ошибками:
https://nakarte.me/#m=13/55.18127/38.94447&l=P/-cseyJuYW1lIjoiZ3VnayA1NiIsInVybCI6Imh0dHBzOi8vbmd3LmZwcGQuY2draXBkLnJ1L3RpbGUvNTYve3p9L3t4fS97eX0ucG5nIiwidG1zIjpmYWxzZSwic2NhbGVEZXBlbmRlbnQiOmZhbHNlLCJtYXhab29tIjoxNCwiaXNPdmVybGF5Ijp0cnVlLCJpc1RvcCI6ZmFsc2V9/J

Здесь на новой карте пропали части дорог и ЛЭПок

**Comment by wladich** [comment]
В общем жду ещё комментариев про полезность этого слоя. От Славы я уже получил мнение, что не выглядит особенно ценным.
Кастомный слой: https://nakarte.me/#m=13/55.18205/39.22617&l=-cseyJuYW1lIjoiZ3VnayA1NiIsInVybCI6Imh0dHBzOi8vbmd3LmZwcGQuY2draXBkLnJ1L3RpbGUvNTYve3p9L3t4fS97eX0ucG5nIiwidG1zIjpmYWxzZSwic2NhbGVEZXBlbmRlbnQiOmZhbHNlLCJtYXhab29tIjoxNCwiaXNPdmVybGF5IjpmYWxzZSwiaXNUb3AiOmZhbHNlfQ==

**Comment by myadzel** [comment]
Карта устаревшая. Причем достаточно сильно в тех местах, которые я хорошо знаю.

**Comment by sikmir** [comment]
Попробовал https://portal.fppd.cgkipd.ru/map?data=eekoers&data=eekomap&data=EekoGMap (`https://ngw.fppd.cgkipd.ru/tile/56/{z}/{x}/{y}.png`), там белые участки в тайлах прозрачные в отличии от ГГЦ. Как я понимаю сейчас нельзя добавить оверлей непрозрачным, `isOverlayTransparent` относится только к печати похоже.

**Comment by wladich** [comment]
isOverlayTransparent это  вообще только для формирования имени pdf.
Для кастомных слоёв сделать непрозрачным нельзя, да.
Но если планируется использование, то, по-моему, надо всё нужное себе скачивать, т.к. скоро оно тоже исчезнет, как и все предыдущие инкарнации. А если скачать, то можно и фон на белый непрозрачный заменить.

**Comment by Xeenych** [comment]
Так а каков вердикт?

**Comment by wladich** [comment]
А, ну 3 человека (включая меня) сказали, что толку от неё мало. Для добавления её надо выкачать целиком и заменить прозрачный фон на белый - а это некоторые расходы времени/усилий и сколько-то сотен гигабайт места.
Так что баланс за то, что бы не добавлять.

**Comment by wladich** [comment]
Последний комментарий был про карты с fppd.cgkipd.ru

Про pkk.rosreestr.ru - надо
* собрать несколько мнений о полезности (и ещё хорошо бы дать мне vpn, чтобы посмотреть ещё раз на неё)
* Если решение положительное - скачать всю карту, захостить, настроить регулярное обновление

**Comment by wladich** [comment]
Ещё про ЕЭКО: подключать напрямую с их сайта я не хочу, т.к. а) в большей части мира недоступно б) могут убрать, в) могут расстроится и заблокировать для моего сайта г) я не могу мониторить доступность д) скорее всего не будет работать печать в pdf и сборка в JNX.
