### ISSUE TITLE
Множественное удаление точек

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#94]
Очень долго, нудно и неудобно (sic!) удалять часть трека двойным кликом по точкам, к тому же, при промахе, они исчезают, приходится опять кликать на трек, чтобы они появились.

**Comment by wladich** [comment]
если надо удалить  с конца трека, то есть backspace/delete

в середине - два раза cut и удалить сегмент (с конца тоже можно)

более удобное решение я не придумал, да и так вроде неплохо

**Comment by myadzel** [comment]
Сегменты. Нет визуального (я не нашел, по крайней мере) способа их отображения (хотя бы их различного цветового кодирования или отображения их начала и конца), направления сегмента (кроме отображения расстояния, но это не очевидно), способа их объединения.

**Comment by myadzel** [comment]
Описываю реальную задачу, с которой не смог справиться ни я, ни еще один человеком (который пользуется nakarte достаточно давно): есть несколько треков с разведки дистанций, в этих треках много "хвостов" (не в начале или конце трека), которые нужно удалить (почистить трек), потом треки нужно объединить в один.

**Comment by wladich** [comment]
Можно сделать в режиме редактирования концевые маркеры другим цветом. Для остального, наверное, надо документацию делать.

**Comment by wladich** [comment]
Удалить и разрезать трек или удалить без разрезания?
Посмотрел на gpsies в Track Creator, не понял, где там удаление полигоном.

**Comment by myadzel** [comment]
Удалить без разрезания.

<img width="1396" alt="screen shot 2018-11-30 at 23 50 31" src="https://user-images.githubusercontent.com/873432/49314231-cfcb2b00-f4fa-11e8-82bb-9e902647b90f.png">

<img width="1396" alt="screen shot 2018-11-30 at 23 50 40" src="https://user-images.githubusercontent.com/873432/49314237-d48fdf00-f4fa-11e8-82c4-9a8d8c02048c.png">

**Comment by wladich** [comment]
Всё равно не понял, как эту фигню у них вызвать...
Но я хочу сделать лучше:

1. В контекстном меню сегмента (не только точки) добавляем пункт типа "Remove part of segment". Т.е. резать можно не только от ноды, но от любого места.
2. При клике на него где-то скраю (наверное, сверху) появляется сообщение на тему "для выбора куска трека для удаления, кликните по треку" (над формулировкой надо подумать)
3. При клике по треку (в любом месте, не обязательно в ноде) часть от первого до второго клика подсвечивается, сообщение меняется на "Точно удалить?", появляется кнопка Ok (Cancel остаётся).
4. Можно ещё раз кликнуть по треку, второй конец выделения при этом перемещается.
5. При нажатии на ok кусок трека вырезается.

Сообщение  из п.2 убирается кнопкой Cancel или по Esc.
Надо продумать, как обрабатываются клики по карте и другие попытки редкатировать треки при наличии сообщения из п.2.

**Comment by myadzel** [comment]
>Всё равно не понял, как эту фигню у них вызвать...

Выставить чекбокс "Select and remove points", затем нарисовать прямоугольник.

**Comment by myadzel** [comment]
Сделал примерно так, как все привыкли работать с gpsies. 

Выделение области курсором только в режиме редактирования трека после нажатия на Ctrl.

**Comment by myadzel** [comment]
Сделал примерно так, как все привыкли работать с gpsies.

Выделение области курсором только в режиме редактирования трека после нажатия на Ctrl.

**Comment by wladich** [comment]
Сделано в #428
