### ISSUE TITLE
Порядок overlay слоёв

### ISSUE THREAD

**Issue by sikmir** [wladich/nakarte#95]
Сейчас при добавлении кастомного overlay слоя он попадает в начало списка и перекрывается всеми другими слоями. Например невозможно посмотреть свои данные поверх ГГЦ слоя. Хотелось бы иметь возможность добавлять свой слой поверх остальных. Или в идеале вообще задавать их порядок.

**Comment by wladich** [comment]
Идея здравая, надо подумать, как это сделать в интерфейсе.

**Comment by wladich** [comment]
Сделал выбор -- кастомный оверлей может быть ниже всех оверлеев или сверху между непрозрачными и прозрачными (т.е. strava, wikimapia и geocaching его будут перекрывать).
Заодно порефакторил диалог редактирования кастомного слоя.
Просьба потестировать на https://stage.nakarte.tk, что всё работает как ожидается, в т.ч., что старые слои читаются (они должны оказаться выше остальных слоёв, т.е. внизу списка)

**Comment by sikmir** [comment]
Well done! It works as expected. Thanks!

**Comment by wladich** [comment]
Не работает при "Place below other layers" -- базовый слой перекрывает кастомный

**Comment by wladich** [comment]
Ещё странные проблемы 
 - при добавлении слоя по ссылке, слой выключается
 - при добавлении слоя по старой ссылке (без isTop) он оказывается сверху списка, хотя у него явно выставляется isTop=True и в диалоге настроек включено "Above other layers"

Релиз откатил

**Comment by wladich** [comment]
Ещё надо протестировать, как работает апгрейд слоя ис localStorage a) если в ссылке был включен, б) если был выключен
Проверить, что не удваивается
