### ISSUE TITLE
сообщение о невалидном треке, если у точки нет имени

### ISSUE THREAD

**Issue by wladich** [wladich/nakarte#98]
name для wpt необязателен, сообщения быть не должно
пример в аттаче
[bad_track.gpx.txt](https://github.com/wladich/nakarte/files/2156458/bad_track.gpx.txt)

**Comment by myadzel** [comment]
Предупреждение сейчас появляется:

>File "bad_track.gpx" is corrupt, loaded data can be invalid or incomplete

**Comment by wladich** [comment]
обновил таск

**Comment by myadzel** [comment]
Уточнение к задаче -- точки не пропускать, добавлять им условное имя, типа "wpt"?
